import type { Improvement, ImprovementTree, Library } from './types.js';

/**
 * Content library seed data, ported verbatim from design/_shared/library.js.
 * Everything here is a *definition*; character sheets reference these by Id and never copy
 * them, so an admin-panel edit reaches every sheet on next render.
 */

/** The 25 Hero Improvement Trees (11 Combat + 14 Narrative), named and themed directly from
 *  Ruleset-V0.5.md's "Hero Improvements" section — real, authored content, unlike the
 *  placeholder nodes built on top of them below. "Command" is named twice in the doc (once per
 *  category) — kept as two distinct trees with the same display Name, disambiguated by Category,
 *  rather than merged into one. */
const IMPROVEMENT_TREE_DEFS: { id: string; name: string; category: 'Combat' | 'Narrative'; description: string }[] = [
  { id: 'it-strike', name: 'Strike', category: 'Combat', description: 'Direct attacks, signature weapons, and straightforward harm.' },
  { id: 'it-smash', name: 'Smash', category: 'Combat', description: 'Overwhelming force, wide destruction, and broken obstacles.' },
  { id: 'it-exploit', name: 'Exploit', category: 'Combat', description: 'Ambushes, marks, counters, and weak points.' },
  { id: 'it-control', name: 'Control', category: 'Combat', description: 'Restraint, forced movement, fear, terrain, and denial.' },
  { id: 'it-maneuver', name: 'Maneuver', category: 'Combat', description: 'Charges, retreats, leaps, flight, teleportation, and repositioning.' },
  { id: 'it-guard', name: 'Guard', category: 'Combat', description: 'Armor, shields, wards, parries, and interposition.' },
  { id: 'it-endure', name: 'Endure', category: 'Combat', description: 'Durability, resistance, recovery, and refusing defeat.' },
  { id: 'it-support', name: 'Support', category: 'Combat', description: 'Healing, cleansing, empowerment, and practical aid.' },
  { id: 'it-command-combat', name: 'Command', category: 'Combat', description: 'Formations, morale, coordination, and directing allies.' },
  { id: 'it-escalate', name: 'Escalate', category: 'Combat', description: 'Stances, reserves, sustained effects, and growing power.' },
  { id: 'it-transform-summon', name: 'Transform & Summon', category: 'Combat', description: 'Battle forms, manifestations, duplicates, and summons.' },
  { id: 'it-sneak', name: 'Sneak', category: 'Narrative', description: 'Concealment, infiltration, disguise, theft, escape, and sabotage.' },
  { id: 'it-traverse', name: 'Traverse', category: 'Narrative', description: 'Journeys, navigation, scouting, mounts, and obstacles.' },
  { id: 'it-sense', name: 'Sense', category: 'Narrative', description: 'Perception, tracking, investigation, divination, and danger.' },
  { id: 'it-study', name: 'Study', category: 'Narrative', description: 'Lore, research, memory, languages, analysis, and learning.' },
  { id: 'it-charm', name: 'Charm', category: 'Narrative', description: 'Persuasion, deception, intimidation, performance, and reputation.' },
  { id: 'it-command-narrative', name: 'Command', category: 'Narrative', description: 'Authority, followers, factions, crowds, and institutions.' },
  { id: 'it-bond', name: 'Bond', category: 'Narrative', description: 'Relationships, loyalty, companions, community, and trust.' },
  { id: 'it-tinker', name: 'Tinker', category: 'Narrative', description: 'Crafting, repair, alchemy, tools, gear, food, and creation.' },
  { id: 'it-excel', name: 'Excel', category: 'Narrative', description: 'Exceptional training, reliable competence, and mastery.' },
  { id: 'it-survive', name: 'Survive', category: 'Narrative', description: 'Rest, supplies, hazards, recovery, and self-sufficiency.' },
  { id: 'it-commit', name: 'Commit', category: 'Narrative', description: 'Oaths, duties, faith, quests, destiny, and redemption.' },
  { id: 'it-scheme', name: 'Scheme', category: 'Narrative', description: 'Plans, flashbacks, contacts, luck, wealth, and contingencies.' },
  { id: 'it-transform-narrative', name: 'Transform', category: 'Narrative', description: 'Changes of identity, form, supernatural nature, and apotheosis.' },
  { id: 'it-shape', name: 'Shape', category: 'Narrative', description: 'Rituals, utility magic, communion, conjuration, and reality.' },
];

const SEED_IMPROVEMENT_TREES: ImprovementTree[] = IMPROVEMENT_TREE_DEFS.map((t) => ({ Id: t.id, Name: t.name, Category: t.category, Description: t.description }));

/** Ruleset-V0.5.md names all 25 trees above but never authors a single node on any of them — no
 *  Starting Improvement, no prerequisite line, nothing (see HANDOFF.md open issue 12). Rather
 *  than invent real mechanical effects that don't exist in the source document, each tree gets
 *  exactly two clearly-labeled placeholder nodes (a Starting Improvement and one node chained to
 *  it) — enough to exercise the DAG gate (`improvementState` in `logic.ts`) and the admin
 *  validation (`validateImprovementDag` in `adminLogic.ts`) end to end. Replace these with real
 *  authored content once the repo owner writes it; nothing else in this slice depends on their
 *  Effect text being real. */
const PLACEHOLDER_IMPROVEMENT_EFFECT = 'Placeholder — Ruleset-V0.5.md names this tree but has not authored its Improvements yet. This node only exists to exercise the prerequisite DAG; replace with real content (see HANDOFF.md open issue 12).';

const SEED_IMPROVEMENTS: Improvement[] = IMPROVEMENT_TREE_DEFS.flatMap((t) => {
  const startId = `im-${t.id.slice(3)}-1`;
  const nextId = `im-${t.id.slice(3)}-2`;
  return [
    { Id: startId, TreeId: t.id, Name: `${t.name} I (Starting, placeholder)`, Effect: PLACEHOLDER_IMPROVEMENT_EFFECT, IsStarting: true, PrerequisiteIds: [] },
    { Id: nextId, TreeId: t.id, Name: `${t.name} II (placeholder)`, Effect: PLACEHOLDER_IMPROVEMENT_EFFECT, IsStarting: false, PrerequisiteIds: [startId] },
  ];
});

export function seedLibrary(): Library {
  return {
    virtues: [
      { Id: 'v-might', Name: 'Might', Tagline: 'Physicality & Force', Essence: 'Your raw power, athleticism, and physical capabilities.', UsageHelperText: 'To smash through a gate, wrestle a beast, or climb a mountain.' },
      { Id: 'v-mettle', Name: 'Mettle', Tagline: 'Willpower & Grit', Essence: 'Your internal fire, your bravery in the face of the unknown, and your spiritual resilience.', UsageHelperText: 'To stare down a dragon’s gaze, resist the temptation of a cursed relic, or keep moving when your legs want to give out.' },
      { Id: 'v-heart', Name: 'Heart', Tagline: 'Bond & Empathy', Essence: 'Your ability to connect with others, to inspire hope, and to act on your deepest convictions.', UsageHelperText: 'To convince a village to stand and fight, comfort a grieving companion, or sacrifice your own safety for the group’s sake.' },
      { Id: 'v-wit', Name: 'Wit', Tagline: 'Perception & Instinct', Essence: 'Your sharpness of mind, your ability to read a room, and your eye for the hidden or the mysterious.', UsageHelperText: 'To find the hidden latch in a ruin, realize an NPC is hiding a secret, or notice the ambush before the arrows fly.' },
      { Id: 'v-guile', Name: 'Guile', Tagline: 'Strategy & Subtlety', Essence: 'Your cleverness, your dexterity, and your ability to outmaneuver or outthink an opponent.', UsageHelperText: 'To sneak past a sentry, pick a complex lock, set a clever trap, or misdirect a foe’s attention during a tense parley.' },
    ],
    conditions: [
      { Id: 'c-exhausted', Name: 'Exhausted', VirtueId: 'v-might', RollPenalty: -2, ClearAction: 'Recover from your exhaustion by indulging in a vice and shirking responsibility.' },
      { Id: 'c-afraid', Name: 'Afraid', VirtueId: 'v-mettle', RollPenalty: -2, ClearAction: 'Come down from your fear by running away from something challenging.' },
      { Id: 'c-hopeless', Name: 'Hopeless', VirtueId: 'v-heart', RollPenalty: -2, ClearAction: 'Absolve your guilt by punishing yourself, or blame a party member related to your guilt.' },
      { Id: 'c-irrational', Name: 'Irrational', VirtueId: 'v-wit', RollPenalty: -2, ClearAction: 'Vent your anger by hurting someone important to you, or damage something important.' },
      { Id: 'c-distracted', Name: 'Distracted', VirtueId: 'v-guile', RollPenalty: -2, ClearAction: 'Get over your insecurity by making a rash action without discussing it with the party.' },
    ],
    armorTypes: [
      { Id: 'a-physical', Name: 'Physical', Key: 'Physical', Description: 'Mundane protection — plate, hide, a shield taken on the arm.' },
      { Id: 'a-heavy', Name: 'Heavy', Key: 'Heavy', Description: 'Bulk that turns a blow aside entirely.' },
      { Id: 'a-special', Name: 'Special', Key: 'Special', Description: 'Warded, blessed, or otherwise uncanny protection.' },
    ],
    items: [
      { Id: 'i-sword', Name: 'Arming sword', LoadCost: 1, Description: 'A soldier’s blade, well balanced and unremarkable.' },
      { Id: 'i-shield', Name: 'Kite shield', LoadCost: 1, GrantsArmorTypeId: 'a-physical', Description: 'Battered oak faced in hide.' },
      { Id: 'i-mail', Name: 'Coat of mail', LoadCost: 2, GrantsArmorTypeId: 'a-heavy', Description: 'Heavy, loud, and worth every pound.' },
      { Id: 'i-bootknife', Name: 'Boot knife', LoadCost: 0, Description: 'Small enough that nobody counts it.' },
      { Id: 'i-rope', Name: 'Coil of rope', LoadCost: 1, Description: 'Fifty feet, hemp, slightly damp.' },
      { Id: 'i-lantern', Name: 'Hooded lantern', LoadCost: 1, Charges: 3, Description: 'Burns oil. Shutter it to hide the light.' },
      { Id: 'i-poultice', Name: 'Field poultices', LoadCost: 0, Charges: 3, Description: 'Spend a charge to clear a Rank of a physical Status.' },
      { Id: 'i-wardstone', Name: 'Ward-stone', LoadCost: 0, Charges: 1, GrantsArmorTypeId: 'a-special', Description: 'Cracks when it saves you. Once.' },
      { Id: 'i-rations', Name: 'Trail rations', LoadCost: 1, Description: 'A week of unpleasant but sufficient food.' },
      { Id: 'i-toolkit', Name: 'Thief’s tools', LoadCost: 0, Charges: 2, Description: 'Picks, wedges, a mirror on a wire.' },
      { Id: 'i-banner', Name: 'House banner', LoadCost: 2, Description: 'Impossible to conceal. That is the point.' },
    ],
    motifs: [
      { Id: 'mo-artisan', Name: 'Artisan', Description: 'You are skilled in a grounded craft or lifelong trade, honed through quiet dedication and practice', SkillTagExamples: ['Armorer', 'Artificer', 'Baker', 'Blacksmith', 'Bowyer and Fletcher', 'Brewer of Potent Spirits', 'Camp Cook', 'Carpenter', 'Cunning Trapmaker', 'Field Medic', 'Inventor', 'Jeweler', 'Leatherworker', 'Locksmith', 'Meticulous Mapmaker', 'Ol’ Stablemaster', 'Reliable Wagonwright', 'Ropemaker and Rigger', 'Seasoned Shipwright', 'Stonemason', 'Tailor', 'Tinker', 'Traveling Apothecary', 'Undertaker’s Trade'], FlawTagExamples: ['A Perfectionist at Heart', 'Always Taking Commissions', 'Can’t Leave It Broken', 'Covered in Grime', 'Dangerous Prototype', 'Debts to the Guild', 'Distracted by Fine Craftsmanship', 'Expensive Materials', 'Fingers Stiff with Age', 'I Know Better Than the Customer', 'My Finest Work Was Stolen', 'Never Enough Time', 'No Proper Workshop', 'Protective of My Tools', 'Rival Artisan', 'The Work Comes First', 'Won’t Use Shoddy Materials'] },
      { Id: 'mo-bearer', Name: 'Bearer', Description: 'You carry a relic of profound power, it has a legacy of magic, mystery, or myth.', SkillTagExamples: ['Alchemist’s Satchel', 'Ancestral Bow', 'Arcane Grimoire', 'Boots That Know the Road', 'Bow of the Moon Hunt', 'Bronze Compass', 'Clockwork Companion', 'Cloak of a Thousand Faces', 'Crown Without a Kingdom', 'Cursed Weapon', 'Dragon Egg', 'Ember of the First Flame', 'Enchanted Armor', 'Flying Carpet', 'Giant’s Iron Gauntlet', 'Holy Relic', 'Horn of the Herd', 'Living Shield', 'Magic Sword', 'Magical Map', 'Mask of the Nameless Saint', 'Master Key', 'Masterwork Thieves’ Tools', 'Mysterious Circlet', 'Ring of Royal Command', 'Seed of the World-Tree', 'Shield of the Last Guardian', 'Spirit Lantern', 'Trickster’s Mask', 'Wizard’s Staff'], FlawTagExamples: ['Coveted by Powerful Enemies', 'Cursed to Keep It Close', 'Draws Unwanted Attention', 'Everyone Thinks It Belongs to Them', 'It Awakens at the Worst Time', 'It Cannot Be Replaced', 'It Remembers Previous Owners', 'It Whispers Temptations', 'Its Power Has a Price', 'Magic Leaves a Trail', 'Must Keep It Secret', 'My Claim Is Questioned', 'Not Yet Worthy', 'Others Suffer When I Use It', 'Protective to a Fault', 'Requires Rare Offerings', 'The Relic Has a Will of Its Own', 'The Relic Is Failing', 'Too Dangerous to Surrender', 'Wanted by Its Creator'] },
      { Id: 'mo-devoted', Name: 'Devoted', Description: 'You have an unshakable loyalty to a cause, creed, or companion.', SkillTagExamples: ['A Light Against Darkness', 'Animal Companion', 'Bodyguard', 'Caregiver', 'Carry Their Memory', 'Compassionate', 'Defender of the Old Ways', 'Dependable', 'Family First', 'Feed the Hungry', 'Friend to All', 'Friend to Every Beast', 'Guardian of Our Village', 'Helpful', 'Hope in Hopeless Places', 'Loyal Companion', 'Mentor', 'Mercy Before Vengeance', 'My Companion Comes First', 'No One Left Behind', 'Patriot', 'Protective', 'Selfless', 'Servant of the Sacred Flame', 'Shield of the Innocent', 'Stand With the Outcast', 'The Cause Above Comfort', 'The Crew Is My Family', 'True Believer', 'Trustworthy', 'Voice of the Common Folk'], FlawTagExamples: ['Can’t Abandon Those in Need', 'Compassion for the Enemy', 'Easily Exploited Loyalty', 'Family Before the Quest', 'Forgives Too Easily', 'I Promised I’d Return', 'My Charge Cannot Protect Themself', 'No One Left Behind', 'Others Depend on Me', 'Refuses a Necessary Sacrifice', 'Someone Always Needs Help', 'Takes the Blame for Companions', 'Their Pain Is Mine', 'Trusts the Wrong People', 'Unable to Say No', 'What If the Cause Is Wrong?', 'Will Not Break a Confidence', 'Won’t Endanger Innocents', 'Won’t Leave the Dead Unburied'] },
      { Id: 'mo-exalted', Name: 'Exalted/Lowly', Description: 'Your rank, reputation, and influence within the intricate webs of society.', SkillTagExamples: ['Arena Champion', 'Beggar', 'Beloved Folk Hero', 'Commoner', 'Courtier', 'Debt-Bound Peasant', 'Decorated Captain', 'Disgraced Knight', 'Disgraced Noble', 'Famous Entertainer', 'Feared Crime Boss', 'Foreign Ambassador', 'Fugitive', 'High Priestess', 'Infamous Outlaw', 'Landed Noble', 'Merchant', 'Pirate Captain', 'Politician', 'Respected Guildmaster', 'Royal Advisor', 'Royal in Exile', 'Royal Spymaster', 'Servant', 'Street Urchin', 'Tavern Keeper', 'Village Elder'], FlawTagExamples: ['A Reputation to Maintain', 'Always Recognized', 'An Embarrassment to My Station', 'Beneath Their Notice', 'Bound by Courtly Etiquette', 'Class Resentment', 'Debts Above My Means', 'Expected to Lead', 'Family Scandal', 'Hated by the Common Folk', 'I Have No Authority Here', 'Mistaken for a Servant', 'My Title Opens the Wrong Doors', 'Old Rivals at Court', 'Orders from Above', 'People Want Favors', 'Poor and Proud', 'Privilege Blinds Me', 'The Law Watches Me'] },
      { Id: 'mo-exemplar', Name: 'Exemplar', Description: 'You have a defining temperament or worldview. Or perhaps some specific physical, mental, or emotional qualities.', SkillTagExamples: ['Affable', 'Always Has a Plan', 'Ambitious', 'Battle-Hardened', 'Bookworm', 'Born Leader', 'Built to Endure', 'Charming', 'Coldly Logical', 'Cowardly', 'Curious to a Fault', 'Disciplined', 'Fearless in the Face of Danger', 'Hands Quicker Than Thought', 'Heart of Gold', 'Hot-Headed', 'Intimidating Presence', 'Iron Stomach', 'Jovial Spirit', 'Keen-Eyed', 'Light on My Feet', 'Lone Wolf', 'Never Forgets a Face', 'Practiced Liar', 'Prankster', 'Quick Study', 'Reckless', 'Silver-Tongued', 'Stubborn as Stone', 'Survivor', 'Unshakably Calm', 'Young and Naive'], FlawTagExamples: ['Always Has to Be Right', 'Can’t Resist a Dare', 'Coward at Heart', 'Craves Attention', 'Easily Flattered', 'Envious of the Gifted', 'Falls for a Pretty Face', 'Holds a Grudge', 'Jumps to Conclusions', 'Laughs at the Wrong Time', 'Never Asks for Help', 'No Patience for Fools', 'Overconfident', 'Painfully Honest', 'Quick to Anger', 'Reckless Curiosity', 'Too Proud to Retreat', 'Trusts Too Easily', 'Vindictive When Crossed', 'Won’t Admit Fear'] },
      { Id: 'mo-fated', Name: 'Fated', Description: 'You walk a prophesied path, divine calling, or inexorable fate.', SkillTagExamples: ['Born Beneath the Red Comet', 'Chosen by a Forgotten God', 'Death Must Wait', 'Doom Follows in My Wake', 'Doomed Hero', 'Dragon Slayer', 'Face My Own Blood', 'Fated Rival', 'Fated to Unite the Realms', 'Fortune Favors the Bold', 'Future Monarch', 'Harbinger', 'Last Hope of My House', 'Last of My Kind', 'Lost Heir', 'Marked by the Gods', 'Marked by Prophecy', 'Miracle Child', 'Promise Across Lifetimes', 'Prophetic Dreamer', 'Reincarnated Hero', 'Sacrificial Hero', 'Survivor Against the Odds', 'The Lost City Calls to Me', 'The Stars Point the Way', 'Unwilling Savior'], FlawTagExamples: ['A Doomed Bloodline', 'Destiny Demands Sacrifice', 'Dreams Reveal Too Much', 'Fate Threatens Those I Love', 'Fear of Becoming the Villain', 'Mistaken for the Chosen One', 'My Destiny Comes Before Everything', 'My Rival Shares My Fate', 'Omens Distract Me', 'Others Want to Control My Destiny', 'Prophecy Is Ambiguous', 'The Future Is Changing', 'The Gods Keep Testing Me', 'The Wrong People Believe in Me', 'Those Who Know the Prophecy Hunt Me', 'What If the Prophecy Is Wrong?'] },
      { Id: 'mo-forged', Name: 'Forged', Description: 'You have been defined by some crucible of your past; a defining trauma, triumph, or event that shaped you.', SkillTagExamples: ['Abandoned Child', 'Betrayed by My Own', 'Cult Survivor', 'Disgraced Soldier', 'Dragon Attack Survivor', 'Escaped the Gallows', 'Exiled for the Truth', 'Fallen Noble', 'Forged in War', 'Former Criminal', 'Former Cultist', 'Fugitive', 'Grew Up on the Streets', 'Nothing Left to Lose', 'Orphan', 'Outcast', 'Plague Survivor', 'Prisoner of War', 'Raised by Monsters', 'Raised in Chains', 'Runaway', 'Scarred', 'Scavenger', 'Shipwreck Survivor', 'Siege Survivor', 'Sole Survivor', 'Trained From Childhood', 'Veteran of the Fighting Pits'], FlawTagExamples: ['Afraid It Will Happen Again', 'Betrayed Once and Trust No One', 'Can’t Forgive Myself', 'Chronic Old Wound', 'Enemies from My Past', 'Flinches at the Reminder', 'Former Master Wants Me Back', 'Hunted for What I Did', 'I Left Someone Behind', 'Nightmares', 'No Mercy for People Like Them', 'Old Habits Die Hard', 'Someone Knows the Truth', 'Survivor’s Guilt', 'The Past Hardened Me', 'Trouble Brings Out the Old Me', 'Unable to Return Home', 'Vengeance Before Duty', 'Won’t Be Helpless Again'] },
      { Id: 'mo-inheritor', Name: 'Inheritor', Description: 'You are greatly affected by the bloodline, culture, and traditions of the people you call your own.', SkillTagExamples: ['Blood of Giant Slayers', 'Child of Two Peoples', 'Court-Bred Scion', 'Descendant of the Old Empire', 'Desert Caravan Folk', 'Desert Nomad', 'Dwarven Stone-Sense', 'Family of Famous Thieves', 'Forest Clan', 'Guildborn and Raised', 'Heir to the Witch-Queens', 'Highlander', 'Horse-Lord', 'It Takes a Village', 'Keeper of Ancestor Songs', 'Last Speaker of the Old Tongue', 'Mountain Clan Hospitality', 'Noble', 'Nomad of the Painted Steppe', 'Pirate Kin', 'Raised by Riverfolk', 'Royal Education', 'Sacred Grove Traditions', 'Salt-Coast Tradition', 'Seafaring People', 'Street-Raised', 'Temple-Raised', 'Under-City Born', 'Warrior Culture', 'World Traveler'], FlawTagExamples: ['Ancestral Feud', 'Bound by Old Customs', 'Clan Before Companions', 'Exiled for my Choices', 'Expected to Marry Well', 'Family Name Opens Old Wounds', 'Foreign Ways Confuse Me', 'Heirloom Obligations', 'I Must Prove My Heritage', 'Inherited Enemies', 'Last to Carry the Tradition', 'My People Need Me', 'Never Fully Accepted', 'Old Prejudices', 'Outsider to Both Worlds', 'Relatives Everywhere', 'Sacred Taboos', 'The Ancestors Are Watching', 'Tradition Forbids It', 'Unwanted Inheritance', 'What Will My People Think?'] },
      { Id: 'mo-mystic', Name: 'Mystic', Description: 'You wield an ability with the unseen or supernatural forces that shape the world.', SkillTagExamples: ['Aura Reader', 'Cleric', 'Curse Breaker', 'Diviner', 'Dreamwalker', 'Druid', 'Elementalist', 'Enchanter', 'Guided by the Stars', 'Hands of Healing Light', 'Hedge Mage', 'Keeper of Wards', 'Listener at the Grave', 'Moon-Touched Illusionist', 'Necromancer', 'Ritualist', 'Rune Speaker', 'Shaman', 'Sorcerer', 'Spellblade', 'Spirit Medium', 'Storm Whisperer', 'Summoner', 'Warlock', 'Wild Magic Channeler', 'Witch', 'Wizard'], FlawTagExamples: ['Can’t Ignore the Arcane', 'Casting Attracts Attention', 'Curious About Forbidden Magic', 'Emotions Unleash My Power', 'Haunted by Spirits', 'Hunters on My Trail', 'Magic Falters Before Cold Iron', 'Must Speak the Incantation', 'Power Hungers for More', 'Rituals Take Too Long', 'Rival Knows My Secrets', 'Spells Leave a Mark', 'Tempted by Easy Power', 'The Unseen Speak Constantly', 'Uncontrolled Visions', 'Vulnerable While Casting', 'Wards I Cannot Cross', 'What Answers Me Isn’t Friendly', 'Wrong Phase of the Moon'] },
      { Id: 'mo-mythic', Name: 'Mythic', Description: 'You are a creature of magic or myth.', SkillTagExamples: ['Angel-Spawn', 'Beastfolk', 'Born of Living Stone', 'Centaur', 'Child of the Deep', 'Clockwork Soul', 'Disembodied Spirit', 'Dragonkin', 'Dryad of the Wandering Grove', 'Dwarf', 'Elf', 'Fair Folk Glamour', 'Fairy', 'Giantkin Might', 'Goblin', 'Gorgon’s Gaze', 'Hearthfolk', 'Hellspawn', 'Living Construct', 'Living Shadow', 'Merfolk', 'Minotaur', 'Moon-Cursed Werebeast', 'Orc', 'Revenant’s Tenacity', 'Shapeshifter', 'Troll-Blooded Regeneration', 'Vampire', 'Voice of the Sphinx', 'Wings of the Harpy'], FlawTagExamples: ['Bound by Ancient Rules', 'Cannot Pass for Mortal', 'Cannot Tell a Direct Lie', 'Creature of Old Hungers', 'Feared on Sight', 'Holy Ground Rejects Me', 'Hunters Track My Kind', 'Instinct Over Reason', 'Iron Burns Me', 'Magic Reveals What I Am', 'My True Form Is Dangerous', 'Natural Enemies Know My Scent', 'No Place Among Mortals', 'Old Stories Get Me Wrong', 'Parts of Me Are Valuable', 'Prone to Transformation', 'Strange Customs', 'The Wild Calls Me Home', 'True Name Holds Power', 'Unnatural Appetite'] },
      { Id: 'mo-sage', Name: 'Sage', Description: 'You carry rare or secret knowledge. Perhaps due to arcane or divine insight, or specialized schooling.', SkillTagExamples: ['Alchemical Theorist', 'Ancient Historian', 'Appraiser', 'Archaeologist', 'Archivist of Prophecy', 'Cartographer of Lost Roads', 'Curator of Curses', 'Doctor', 'Genealogist of Great Houses', 'Herbalist of the Wilds', 'Investigator', 'Librarian', 'Magical Historian', 'Monster Lore', 'Occult Researcher', 'Planar Cosmologist', 'Religious Scholar', 'Scholar', 'Scholar of Forbidden Magic', 'Scribe', 'Student of the Heavens', 'Translator'], FlawTagExamples: ['Can’t Leave a Mystery Unsolved', 'Dangerously Curious', 'Forbidden Knowledge Tempts Me', 'Forgets Practical Matters', 'Knowledge Others Would Kill For', 'Must Consult the Texts', 'Needs Better Evidence', 'No Field Experience', 'Overcomplicates Everything', 'Poor Under Pressure', 'Research Takes Time', 'Rival Scholar', 'Speaks in Unhelpful Jargon', 'Theory Before Common Sense', 'Trusts the Written Word Too Much', 'Unable to Admit Ignorance'] },
      { Id: 'mo-sworn', Name: 'Sworn', Description: 'You’ve sworn a solemn oath, sacred mission, or heavy mantle.', SkillTagExamples: ['Avenge the Fallen', 'Bounty Hunter', 'Break Every Chain', 'Bring Them Back Alive', 'Carry the Message', 'Crown’s Champion', 'Defend Sacred Ground', 'Demon Hunter', 'Finish What I Begin', 'Inquisitor', 'Keeper of Secrets', 'Lawkeeper', 'Monster Hunter', 'Never Draw First Blood', 'Never Refuse a Worthy Challenge', 'Oath of Allegiance', 'Paladin', 'Pay Every Debt', 'Protect the Heir', 'Questing Knight', 'Reclaim My Family’s Honor', 'Relic Seeker', 'Return the Stolen Crown', 'Royal Guard', 'Sacred Warden', 'Slay the Deathless King', 'Speak No Lies', 'Sworn Sword', 'Witch Hunter'], FlawTagExamples: ['Bound to an Unworthy Master', 'Cannot Break My Word', 'Cannot Turn Away from My Sworn Enemy', 'Duty Before Friendship', 'Failure Means Disgrace', 'I Must Answer Every Challenge', 'Must Bring Them Back Alive', 'My Oath Forbids the Easy Path', 'No Mercy for Oathbreakers', 'No Rest On My Quest', 'Orders Conflict with Conscience', 'Promises Keep Accumulating', 'Protect the Heir at Any Cost', 'Refuses Dishonorable Tactics', 'The Target May Be Innocent', 'Vengeance Clouds My Judgment'] },
      { Id: 'mo-virtuoso', Name: 'Virtuoso', Description: 'You display a breathtaking raw talent, hard-won skill, or impressive mastery.', SkillTagExamples: ['Assassin', 'Battlefield Tactician', 'Berserker', 'Blade Dancer', 'Circus Performer', 'Con Artist', 'Daring Acrobat', 'Deadeye Archer', 'Enthralling Orator', 'Escape Artist', 'Fancy Footwork', 'Fearless Beast Rider', '“Legendary” Gambler', 'Martial Artist', 'Master Lockpick', 'Master of Disguise', 'Master of Tongues', 'Navigator', 'Peerless Duelist', 'Ranger', 'Rooftop Runner', 'Seasoned Monster Hunter', 'Silver-Voiced Bard', 'Sleight-of-Hand Artist', 'Swashbuckler', 'Thief', 'Uncanny Tracker', 'Weaponmaster'], FlawTagExamples: ['A Rival Wants My Title', 'Always Showing Off', 'Can’t Resist a Challenge', 'Competition Brings Out My Worst', 'Everyone Expects Perfection', 'Has a Tell', 'Jealous of Greater Talent', 'Must Practice Constantly', 'No Patience for Amateurs', 'Overconfident in My Specialty', 'Pride Before Caution', 'Recognized by My Style', 'Requires Specialized Equipment', 'The Audience Matters Too Much', 'The Show Must Go On', 'Too Clever by Half', 'Tries the Impossible', 'Weak Outside My Specialty'] },
    ],
    improvementTrees: SEED_IMPROVEMENT_TREES,
    improvements: SEED_IMPROVEMENTS,
    moves: [
      { Id: 'm-defiant', Name: 'Stand Defiant', Kind: 'Basic', VirtueId: 'v-mettle', Description: 'When you weather an assault on the mind, body, or spirit, try to resist the urge to flee, or endure excruciating agony to hold your ground and stand defiant against it, roll +Mettle.', Results: { Tier3: { Description: 'You are unshakeable. You shrug off the pressure and gain a momentary advantage — take +1 forward against the source of the threat.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'You hold firm, but the effort costs you. Choose one:', ChooseCount: 1, Options: ['You feel shaken from the conflict; mark a Condition.', 'You don’t come out unscathed. Take Rattled 2 (or similar).', 'To push through costs you. Make a sacrifice to do it — name what that is and the GM will tell you if it is enough.'] }, Tier1: { Description: 'The pressure breaks you. You flinch, flee, or collapse, and the GM makes a move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-solace', Name: 'Offer Solace', Kind: 'Basic', VirtueId: 'v-heart', Description: 'When you try to comfort or support someone by offering solace and speaking from the heart, roll +Heart.', Results: { Tier3: { Description: 'If they open up to you, they either mark Potential, clear a Condition, or you reduce one of their negative Statuses by 2 Ranks (or increase a positive Status by 2). Additionally, mark Rapport or mark Bond with them.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'If they open up to you, they either mark Potential, clear a Condition, or shift a Status 2 Ranks.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'Your approach was completely wrong. Mark a Condition or lose one Bond mark with them.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-sway', Name: 'Sway the Spirit', Kind: 'Basic', VirtueId: 'v-heart', Description: 'When trying to sway the spirit by using empathy, honesty, or comfort to get someone to do what you want, roll +Heart.', Results: { Tier3: { Description: 'They do as you ask to the best of their ability. If you’ve asked too much, they’ll tell you what it would take for them to do it.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They are willing, but the GM will choose one:', ChooseCount: 1, Options: ['Gain Indebted 2. You owe them a promise, a payment, or a favor in return. The more you ask, the more they’ll ask in return. They may demand it upfront.', 'They only follow through on a portion of your request, or will only do it after revealing a hard truth to you. GM’s choice.', 'The act or their answer puts them in danger; take −1 forward with them due to the friction.'] }, Tier1: { Description: 'You reveal a vulnerability or offend them. If they choose to do what you ask, the favor you must do for them is particularly costly, challenging, or undignified. In any situation, the GM makes a Hard Move.', Options: [], ChooseCount: 0 } }, PlayerVariantResults: { Tier3: { Description: 'They mark Potential or Bond between you, and get +1 forward if they do what you ask.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They mark Potential or Bond between you if they do what you ask.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'It’s up to that player to decide how badly you offend or annoy them. Remove one Bond mark between you. They mark Potential if they do not do what you asked.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-truth', Name: 'Discern the Truth', Kind: 'Basic', VirtueId: null, Description: 'When trying to discern the truth by scrutinizing someone in a probing conversation, roll +Wit. When observing someone in a moment of vulnerability, roll +Heart.', Results: { Tier3: { Description: 'Hold 2 and gain Insightful 2. While interacting with them, spend your hold 1-for-1 to ask a question of either the GM or player; they must answer truthfully.', ChooseCount: 0, Options: ['Are they telling the truth about ______?', 'What are they truly feeling?', 'What are their real intentions?', 'What do they wish I would do?', 'How could I get them to ______?', 'What do they desire or fear?'] }, Tier2: { Description: 'Hold 1 and gain Insightful 1, but choose one complication. While interacting with them, spend your hold 1-for-1 to ask a question; they must answer truthfully.', ChooseCount: 1, Options: ['You find your answers the hard way. Mark a Condition.', 'What you find out puts you in imminent danger.', 'You reveal something to your enemies.'] }, Tier1: { Description: 'You misread them completely, believing a complete untruth, or your pursuits reveal something important to your enemies. Mark Potential and the GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } }, HoldGrant: { Tier3: 2, Tier2: 1 } },
      { Id: 'm-assess', Name: 'Assess the Situation', Kind: 'Basic', VirtueId: 'v-wit', Description: 'When you assess the situation to figure out what is going on in a moment of risk or conflict, roll +Wit. If no risk or conflict is present, say how you do it to ask the GM any question.', Results: { Tier3: { Description: 'Hold 3. Take +1 ongoing while acting on any answers.', ChooseCount: 0, Options: ['What here is concealed by magical or mundane means?', 'What’s my best way out, in, or through?', 'What here can I use to ______?', 'Who or what here is the greatest threat, or in the greatest danger?', 'What is the true nature of ______?', 'How can we best end this quickly?'] }, Tier2: { Description: 'Hold 1, or hold 2 and choose one complication. Take +1 ongoing while acting on any answers.', ChooseCount: 1, Options: ['You find your answers the hard way. Mark a Condition.', 'What you find out puts you in imminent danger; the GM will say how after you choose this.', 'There’s a complication either with what you find or how you find it. Take a negative Status at Rank 2.', 'You reveal something to your enemies by leaving something behind or by other means.', 'Your investigation draws immediate and unwanted attention.'] }, Tier1: { Description: 'You find your answer, but it is the worst possible news. Mark Potential and the GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } }, HoldGrant: { Tier3: 3, Tier2: 1 } },
      { Id: 'm-past', Name: 'Consult the Past', Kind: 'Basic', VirtueId: 'v-wit', Description: 'When you search your memory for lore, history, or professional knowledge regarding a subject, consult the past. State how you might know this and roll +Wit. If you have access to a book or similar record, roll with advantage.', Results: { Tier3: { Description: 'The GM will tell you the detailed, useful truth. You and any allies you brief take +1 Ongoing while acting on this knowledge, and gain Prepared 2.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'The GM will tell you a vague or incomplete truth. The information may reveal a new complication or danger. You and any allies you brief take +1 Forward while acting on this knowledge, and gain Prepared 2.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'The answer reveals how bad things really are, or a danger you’re barreling toward. The GM makes a move.', Options: [], ChooseCount: 0 } }, AdvantageTrigger: 'selfReport' },
      { Id: 'm-lead', Name: 'Follow a Lead', Kind: 'Basic', VirtueId: 'v-guile', Description: 'When you try to find something or someone by asking around, tracking a trail, or opening up your senses, roll +Guile. If you are following a lead by gathering rumors and information, you may spend 1 Wealth to roll with advantage.', Results: { Tier3: { Description: 'Choose one dilemma below. Then you find them or it. You may ask one follow-up question about the destination or the journey.', ChooseCount: 1, Options: ['The search has many obstacles and detours. All PCs in pursuit mark a Condition or take Fatigue 2.', 'You’ve been noticed. It may be by your quarry, or by someone or something else.', 'You’ve been held up. Some significant obstacle now stands in your way.', 'Your pursuit reveals information or a vulnerability to your quarry or their allies.', 'You find them, but it takes too much time. The GM advances a threat.', 'You find the lead, but it reveals something that complicates your mission.'] }, Tier2: { Description: 'Choose two dilemmas below. Then you find them or it.', ChooseCount: 2, Options: ['The search has many obstacles and detours. All PCs in pursuit mark a Condition or take Fatigue 2.', 'You’ve been noticed. It may be by your quarry, or by someone or something else.', 'You’ve been held up. Some significant obstacle now stands in your way.', 'Your pursuit reveals information or a vulnerability to your quarry or their allies.', 'You find them, but it takes too much time. The GM advances a threat.', 'You find the lead, but it reveals something that complicates your mission.'] }, Tier1: { Description: 'You find what you’re looking for, but at great cost. Choose three dilemmas. The GM then makes a move.', ChooseCount: 3, Options: ['The search has many obstacles and detours. All PCs in pursuit mark a Condition or take Fatigue 2.', 'You’ve been noticed. It may be by your quarry, or by someone or something else.', 'You’ve been held up. Some significant obstacle now stands in your way.', 'Your pursuit reveals information or a vulnerability to your quarry or their allies.', 'You find them, but it takes too much time. The GM advances a threat.', 'You find the lead, but it reveals something that complicates your mission.'] } }, AdvantageTrigger: 'wealthSpend' },
      { Id: 'm-expertise', Name: 'Invoke Expertise', Kind: 'Basic', VirtueId: null, Description: 'When you attempt to overcome an obstacle or take out enemies not worth Combat using a relevant Skill or Background, say your goal and roll + an appropriate Virtue. The GM will tell you if what you are trying to do can’t be accomplished.', Results: { Tier3: { Description: 'You do what you intended; describe what it looks like.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'Your actions leave you vulnerable. You do what you intended but must choose one consequence:', ChooseCount: 1, Options: ['Gain Exposed 2 and draw unwanted attention or leave a traceable trail.', 'Gain Compromised 2 and the situation escalates; you run out of the frying pan and into the fire.', 'Gain Delayed 2 and you take too long; the situation around you changes in a meaningful way.', 'Attrition: expend a resource or break a useful item.', 'Sacrifice: you receive a worse outcome, hard choice, or price to pay.'] }, Tier1: { Description: 'Your skills and training aren’t enough here. The GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-risk', Name: 'Take a Risk', Kind: 'Basic', VirtueId: null, Description: 'When you attempt to overcome an obstacle or take out enemies not worth Combat without a relevant Skill or Background, say your goal and roll + an appropriate Virtue.', Results: { Tier3: { Description: 'You achieve your goal, but at a cost; choose one consequence.', ChooseCount: 1, Options: ['Attrition: expend a resource or break a useful item.', 'Detection: draw unwanted attention or leave a traceable trail.', 'Danger: the situation escalates.', 'Delay: you take too long; the situation changes meaningfully.', 'Sacrifice: a worse outcome, hard choice, or price to pay.'] }, Tier2: { Description: 'You achieve your goal, but things get messy. The GM chooses one consequence.', ChooseCount: 1, Options: ['Attrition: expend a resource or break a useful item.', 'Detection: draw unwanted attention or leave a traceable trail.', 'Danger: the situation escalates.', 'Delay: you take too long; the situation changes meaningfully.', 'Sacrifice: a worse outcome, hard choice, or price to pay.'] }, Tier1: { Description: 'Things go south. The GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-push', Name: 'Push Yourself', Kind: 'Adventure', VirtueId: null, Description: 'When you push yourself past what you should be able to do, mark a Condition and take +1 to the roll. You may add a further +1 if a Skill applies.', Results: { Tier3: { Description: 'You do it, and it costs only what you already paid.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'You do it, but take a negative Status at Rank 2 of the GM’s choosing.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'You fall short and the Condition is spent for nothing. The GM makes a move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-camp', Name: 'Make Camp', Kind: 'Adventure', VirtueId: null, Description: 'When you make camp in relative safety, clear 2D6 Ranks of negative Statuses and 1D6 Ranks of positive Statuses across the party, refresh all Armor, and choose your Load for the next leg of the journey.', Results: { Tier3: { Description: 'No roll. Camp always works — the question is what it costs you in time.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-session', Name: 'End the Session', Kind: 'Adventure', VirtueId: null, Description: 'At the end of each session, mark Rapport. Then, as a table, name what changed and who changed it.', Results: { Tier3: { Description: 'No roll.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-strike', Name: 'Strike a Nerve', Kind: 'Basic', VirtueId: null, Description: 'When you try to strike the nerve by using manipulation, provocation, or threats to get someone to do what you want or force a reaction, roll +Might or +Guile.', Results: { Tier3: { Description: 'They take the bait and do what you intended, the best that they can. Give them an appropriate Negative Status, Rank 3.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They can instead choose one:', ChooseCount: 1, Options: ['They slip: they reveal a tactical detail or a "tell" you can use later.', 'They stumble: gain a critical opportunity and take +1 forward against them.', 'They scare: they gain the Scared of ___ 2 Status, where ___ is you.'] }, Tier1: { Description: 'They turn the tables. They may call your bluff or use your pressure as a reason to strike back at you. Either way the GM takes or holds a hard move.', Options: [], ChooseCount: 0 } }, PlayerVariantResults: { Tier3: { Description: 'Mark Rapport if they do what you ask.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They mark Potential or Bond between you if they do what you ask.', Options: [], ChooseCount: 0 }, Tier1: { Description: "It's up to that player to decide how badly you offend or annoy them. Remove one Bond mark between you. They mark Potential if they do not do what you asked.", Options: [], ChooseCount: 0 } } },
      { Id: 'm-flashback', Name: 'Recall a Flashback', Kind: 'Adventure', VirtueId: null, Description: "At any point (maybe outside of Combat), a player can Recall a Flashback to take an action in the past that has relevance to their current situation — the action must make sense to have happened. Recalling a Flashback gives you the negative Status Strained, Ranked by severity: 1 for any ordinary action you could have easily done, 2 for an action with a possibility of complication, 3+ for an intricate or detailed action or set of actions. If the recalled action would call for a Move, you still roll for that Move and consequences happen accordingly — you can't roll Resistance against this, and you can't use it to undo a consequence or something that has already occurred.", Results: { Tier3: { Description: "No roll of its own — triggers whichever Move applies to the recalled action.", Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-recuperate', Name: 'Recuperate', Kind: 'Adventure', VirtueId: null, Description: 'Spend a Recovery to clear 1D6 + Mettle Ranks of a single Status.', Results: { Tier3: { Description: 'No roll — see Heal a Status.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-levelup', Name: 'Level Up', Kind: 'Adventure', VirtueId: null, Description: "After you Make Camp, if a Motif has 5 or more Potential, clear that Motif's Potential Track and choose one: add a Skill Tag, add or remove a Flaw Tag, or gain a Hero Improvement — a Starting Improvement on any Improvement Tree, or one connected by a line to an Improvement you already hold on that same tree. Each Improvement can only be chosen once. In fiction, at the Camp, you may choose to describe how the party sees your new advancement.", Results: { Tier3: { Description: 'No roll.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-progress', Name: 'Progress the Party', Kind: 'Adventure', VirtueId: null, Description: 'After you Make Camp, if your Party has 5 or more Rapport, clear the Rapport Track and choose one unique option: add a Skill Tag for your Party Motif, add or remove a Weakness Tag, or gain a Party Improvement — a Starting Improvement on any Improvement Tree, or one connected by a line to an Improvement you already hold on that same tree. Each Improvement can only be chosen once. In fiction, at the Camp, you may choose to describe how you establish your new advancement.', Results: { Tier3: { Description: 'No roll.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-forge', Name: 'Forge a Bond', Kind: 'Adventure', VirtueId: null, Description: 'After you Make Camp, if you and another PC have a Bond Track of 5 or more between you, you may agree to empty it and increase your Bond Level by 1 (maxing out at 5). Each Bond Level has moves and abilities associated with it — take one available to your new Bond Level or lower. In fiction, at the Camp, you may choose to play out a scene demonstrating the connection you two hold. If you do so, mark one Potential each.', Results: { Tier3: { Description: 'No roll — see the Bond handshake.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-aid', Name: 'Aid', Kind: 'Adventure', VirtueId: null, Description: 'Anyone in the Party can Aid another Hero by removing one Rapport from the Rapport Track to give any other party member +1 on any roll, even after the dice are rolled. In order to spend Rapport this way, the spender needs to truly be able to help — describe how you do so in fiction before giving the +1. Any and all party members can spend Rapport from the Track to help on that same roll, though each teammate can only spend once. Using Rapport this way can take a total miss to a complete success.', Results: { Tier3: { Description: 'No roll of its own — this spends Rapport on someone else’s roll. See Rapport.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-watch', Name: 'Keep Watch', Kind: 'Adventure', VirtueId: null, Description: 'If you Make Camp somewhere potentially dangerous or vulnerable, before heading out on the next leg of your journey the Party can Keep Watch. The players choose a volunteer to lead the watch, and the GM rolls 2d6 with no Virtue and may reveal the result (see Results below). Once the watch begins, the GM can make their move from the list at any time. Then the volunteer rolls +an appropriate Virtue (aided by Rapport as normal): on a 10+ choose two, on a 7-9 choose one — You’re alert (gain Alert 2 and rally your party in time); You choose the turf (get the drop on what’s coming and set up where you choose); You use your senses (ask the GM two questions about what is approaching). On a 6-, whatever it is reaches you before you notice — the GM takes or holds a Hard Move. If the party chooses not to Keep Watch and a threat rears its head, treat it as if the Party rolled a 6- on this Virtue roll.', Results: { Tier3: { Description: 'The night passes without incident.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'The GM chooses one:', ChooseCount: 1, Options: ['The person on watch notices something interesting nearby.', 'One party member of the GM’s choosing doesn’t get much sleep. They wake with Restless 2.', 'Something dangerous approaches. If the person on watch has Alert or similar, they may rally the party in time.'] }, Tier1: { Description: 'Everyone marks Potential, and a danger will emerge tonight.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-journey', Name: 'Undertake a Journey', Kind: 'Adventure', VirtueId: null, Description: 'When you gather your party and venture forth on the first or next leg of your Journey: choose your Loadout (Light, Medium, or Heavy — only after Making Camp or Enjoying Downtime), then state your destination and decide your route. A safe destination with no time pressure just happens — describe or play it out, and the GM says how long it took. Otherwise, Undertake a Perilous Journey: the GM says how many times you’ll need to Make Camp to arrive (the answer may be zero), and each time you set out from Camp you Undertake another Perilous Journey until you arrive.\n\nA Perilous Journey has two phases, one player for each. Scout Ahead first (roll +Wit): on a 10+ choose two, on a 7-9 choose one — you notice signs of nearby danger and gain Alert 2; you discern a beneficial aspect of the terrain and gain an appropriate Status 2; you get the drop on whatever lies ahead and gain Prepared 2; you make an interesting discovery. On a 6-, mark Potential and the GM makes a move. If there isn’t time to Scout Ahead, Venture Forth at Disadvantage instead.\n\nThen Venture Forth (roll +Guile): on a 10+ you avoid dangers and reach your destination or a safe place to Make Camp, choosing one from the list below and gaining +1 Ongoing to future rolls on this Journey; on a 7-9 the GM chooses one from the list before you arrive; on a 6- you make it, but mark Potential and the GM makes a move — you encounter a significant person, place, or opportunity; you discover something noteworthy the Scout missed; the trip takes longer than planned (everyone marks a Condition or the GM advances a Threat); something or someone is following you. Rapport can be spent to Aid either roll as normal.', Results: { Tier3: { Description: 'No roll of its own — see Scout Ahead and Venture Forth above.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-downtime', Name: 'Enjoy Downtime', Kind: 'Adventure', VirtueId: null, Description: 'When you spend a few days or more in a safe location, do as many of the following as you like or can afford — anything available at Make Camp is also available here. Rest: spend 1 Wealth to remove all Status Ranks (can be done during any other activity). Recover: an action that would clear one Condition instead clears all Conditions (can be done during any other activity). Carouse: for each involved party member, spend 1 Treasure to revel — everyone involved marks 1 Bond with another involved party member. Acquire: spend Wealth to procure new items and equipment, repair gear, refresh stock, or acquire services. Train: spend 1 Wealth to mark Potential. Pivot: change your personal Drive, or as a party change the Party Goal. Advance: describe starting or pursuing a long-term project — the GM defines its clock, and some projects require others to be completed first — then roll +an appropriate Virtue (see Results below). When everyone is done, decide whether days, weeks, or months passed; the GM sets the next scene and advances Bad Guy clocks appropriately.', Results: { Tier3: { Description: 'Advance marks 3 segments on the project’s clock. Every other activity above has no roll of its own.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'Advance marks 2 segments.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'Advance marks 1 segment.', Options: [], ChooseCount: 0 } } },
    ],
    glossary: [
      { Id: 'g-condition', Name: 'Condition', Aliases: ['Conditions'], Definition: 'A marked penalty tied to one of your five Virtues, taken when a move tells you to "mark a Condition." Each Virtue has one specific Condition (Exhausted, Afraid, Hopeless, Irrational, Distracted) that applies a roll penalty to actions using that Virtue until cleared.' },
      { Id: 'g-rapport', Name: 'Rapport', Aliases: [], Definition: 'A party-wide track marked when a move tells you to "mark Rapport." Filling it clears the track and raises Party Level by 1 — see Improvement. Rapport can also be spent directly as Aid — see Aid.' },
      { Id: 'g-motif', Name: 'Motif', Aliases: ['Motifs'], Definition: 'One of the three core aspects of your Hero — each a bucket for its own Skill Tags, Flaw Tags, a Potential track, and a Quest. You choose three Motifs at creation (from the thirteen suggested, or your own) and may rename any of them to fit your character.' },
      { Id: 'g-skill-tag', Name: 'Skill Tag', Aliases: ['Skill Tags'], Definition: 'A freeform word or phrase under a Motif describing something your Hero is good at. Declare a relevant Skill Tag before a roll to add +1; if more than one applies you may Push Yourself, mark a Condition, and add another +1.' },
      { Id: 'g-flaw-tag', Name: 'Flaw Tag', Aliases: ['Flaw Tags'], Definition: 'A freeform word or phrase under a Motif describing a limit or weakness. A relevant Flaw Tag gives -1 to the roll, and acting on it marks Potential on that Motif whether the roll succeeds or fails.' },
      { Id: 'g-quest', Name: 'Quest', Aliases: ['Quests'], Definition: 'A short, player-written goal hanging off one Motif, tracked with three Act Breaks and three Forsakes. Three Act Breaks complete it; three Forsakes abandon it.' },
      { Id: 'g-potential', Name: 'Potential', Aliases: [], Definition: 'A track on each Motif, marked when a move tells you to "mark Potential" (or when you act on a Flaw Tag). Filling a Motif’s track clears it, raises Level by 1, and lets you add a Skill Tag, add or remove a Flaw Tag, or gain a Hero Improvement — see Improvement.' },
      { Id: 'g-improvement', Name: 'Improvement', Aliases: ['Improvements', 'Improvement Tree', 'Hero Improvement'], Definition: 'A permanent pick taken off one of 25 Hero Improvement Trees (11 Combat, 14 Narrative) when a full Motif Potential track clears. Each tree is its own small prerequisite chain: take a tree’s Starting Improvement any time, or any other Improvement on that tree once you already hold one it connects to. Each Improvement can only be taken once. Party Improvements are named in the rules the same way but have no authored trees yet.' },
      { Id: 'g-hold', Name: 'Hold', Aliases: [], Definition: 'A pool of uses granted by a move on a strong hit, spent one at a time — often to ask questions or trigger a listed effect — until it runs out.' },
      { Id: 'g-load', Name: 'Load', Aliases: [], Definition: 'How much you can carry. Each Item has a Load cost (0, 1, or 2); your total carried Load is capped by your Light/Normal/Heavy tier.' },
      { Id: 'g-bond', Name: 'Bond', Aliases: ['Bonds', 'Mark Bond', 'Bond Track', 'Bond Level'], Definition: 'The relationship between two characters, tracked separately from either character’s sheet, plus the 0–5 Bond Track that measures it — marked when a move tells you to "mark Bond" with someone. Filling the Track lets the pair Forge it, raising Bond Level by 1 (to a maximum of 5) and emptying the Track again. Marking Bond and Forging both go through a propose/accept/reject handshake between the two players; spending Bond, unlike either of those, applies immediately with no handshake. A Bond that reaches Level 5 with a full Track locks — its Level can no longer drop, and no more Bond can be spent on it.' },
      { Id: 'g-status', Name: 'Status', Aliases: ['Statuses'], Definition: 'A named condition (positive or negative) applied by a move, tracked as a row of six boxes rather than a single number — distinct from a Condition, which is always one of the five Virtue-linked penalties. A Status’s Rank is whichever box is marked farthest along the row, not a count of marked boxes. Gaining Rank N marks box N, or the next empty box to its right if N is already marked; reducing a Status clears marks from the top (highest box) down. Box 6 is the Subdued overflow, and Rank 4 is Unstable — see Subdued and Unstable.' },
      { Id: 'g-crumble', Name: 'Crumble', Aliases: [], Definition: 'What happens when you need to mark a Condition but all five are already marked. You leave the scene — unconscious, fleeing, or otherwise — and then clear one Condition of your choice. If this happens in Combat, you also gain Vulnerable 4, and can only act to flee or hold your ground.' },
      { Id: 'g-subdued', Name: 'Subdued', Aliases: [], Definition: 'What happens when a Negative Status would reach Rank 6 (its sixth box). You can’t act regarding that Status until it’s resolved — choose to take a Scar, Risk Death, or go out in a Blaze of Glory.' },
      { Id: 'g-scar', Name: 'Scar', Aliases: ['Scars'], Definition: 'A near-permanent consequence taken instead of dying at Subdued — a lost limb, a lingering nightmare, an unwanted transformation. If your Scars ever outnumber your Level, you must retire from the party.' },
      { Id: 'g-recovery', Name: 'Recovery', Aliases: ['Recoveries'], Definition: 'A limited pool spent to heal a Status — clears 1d6 + Mettle Ranks off a single Status. Refills to your maximum at Make Camp. Hitting 0 Recoveries marks your Exhausted Condition.' },
      { Id: 'g-toughness', Name: 'Toughness', Aliases: [], Definition: 'How much an enemy blunts incoming Status Ranks in Combat. Medium subtracts 2 from any Rank given to it; Heavy treats the Rank as though it had been rolled one tier lower.' },
      { Id: 'g-range', Name: 'Range', Aliases: [], Definition: 'How far apart two combatants are: Melee, Close, Far, Very Far, or Out of Range. Maneuver and Shift move you between bands; Engage at Range and Engage in Melee each only work at their own band.' },
      { Id: 'g-unstable', Name: 'Unstable', Aliases: [], Definition: 'What a Status is called once it reaches Rank 4 (its fourth box). Unstable has no effect by itself — it’s a threshold other moves and rules can key off, so check whether anything you have cares about a Status being Unstable.' },
      { Id: 'g-aid', Name: 'Aid', Aliases: [], Definition: 'Spend 1 Rapport to give another Hero +1 on a roll, even after the dice are already rolled. You can Aid the same roll once per teammate, and Aid from multiple teammates stacks. During Risk Death, Aid costs double — 2 Rapport per +1.' },
      { Id: 'g-wealth', Name: 'Wealth', Aliases: [], Definition: 'A personal resource, freely adjusted on the sheet. Named sinks: spend 1 to roll Follow a Lead with Advantage, or during Enjoy Downtime to Rest, Acquire, or Train.' },
      { Id: 'g-treasure', Name: 'Treasure', Aliases: [], Definition: 'A personal resource, freely adjusted on the sheet like Wealth. Named sink: spend 1 per involved party member to Carouse during Enjoy Downtime.' },
      { Id: 'g-advantage', Name: 'Advantage', Aliases: ['Disadvantage'], Definition: 'Roll 3d6 and keep the best two (Advantage) or worst two (Disadvantage) instead of the usual 2d6. A handful of Moves name a concrete trigger this app can detect — Follow a Lead for 1 Wealth, having a written record for Consult the Past — everything else is a GM call the app leaves to the table.' },
      { Id: 'g-attrition', Name: 'Attrition', Aliases: [], Definition: 'A consequence on Invoke Expertise and Take a Risk: expend a resource or break a useful item. V0.5 never says which resource, so this app doesn’t automate it — deciding what to spend is a table call.' },
      { Id: 'g-camp-asset', Name: 'Camp Asset', Aliases: ['Camp Assets'], Definition: 'A magic item the party is afforded at creation to help them set up camp, leveling up through Tiers as the party progresses. Pick one from the library, or write your own on the spot.' },
      { Id: 'g-camp-action', Name: 'Camp Action', Aliases: ['Camp Actions'], Definition: 'One of a handful of things each player may do at Make Camp — set or change the Party Goal, change a personal Motif Quest, use a Camp Asset, or progress a personal project Clock. Each player gets Party Level + 1 of these per Camp.' },
      { Id: 'g-villain', Name: 'Villain', Aliases: ['Villains'], Definition: 'The antagonist driving an Adventure’s conflict — a monster, person, or anomaly with a Goal, a Scar, Skill Tags, Resources, Powers, Attacks, Resistances and Vulnerabilities, and Status Limits. A Villain doesn’t need to be killed or even defeated to conclude an Adventure — their Goal only needs to be thwarted.' },
      { Id: 'g-npc', Name: 'NPC', Aliases: ['NPCs', 'Non-Player Character'], Definition: 'A supporting-cast character with a Type (their function to you as a GM — Meddler, Minion, Gossip, Ally, Guard, Opportunist, Skeptic, Victim, or Witness), a Goal, and Skill Tags. A Combatant NPC gets Status Limits, same as an Enemy.' },
      { Id: 'g-location', Name: 'Location', Aliases: ['Locations'], Definition: 'A place the Heroes are expected to spend time during an Adventure — 3 Aspects the Heroes can interact with, plus a Location Type (Nexus, Deathtrap, Lair, Citadel, Lab, Archive, Labyrinth, Gaol, or Wilds) describing its purpose.' },
    ],
    enemies: [
      { Id: 'en-brigand', Name: 'Brigand', Description: 'A rank-and-file thug, more dangerous in numbers than alone.', IsBoss: false, Toughness: 'None', StatusLimits: [{ StatusName: 'Hurt', Limit: 4 }, { StatusName: 'Scared', Limit: 3 }] },
      { Id: 'en-warden', Name: 'Iron Warden', Description: 'A plated sentinel bound to guard a single door until it falls.', IsBoss: false, Toughness: 'Heavy', StatusLimits: [{ StatusName: 'Hurt', Limit: 6 }] },
    ],
    /** Ruleset-V0.5.md never names an actual Camp Asset — only the generic concept ("a magic camp
     *  item that facilitates setting up their camp... it levels up as they progress into the
     *  tiers"). These three are illustrative starting examples, same spirit as the two seeded
     *  Enemies above; a party can also just write their own ad-hoc one at Camp (see
     *  `PartyCampAsset`). */
    campAssets: [
      { Id: 'ca-tent', Name: 'Ever-Warm Tent', Description: 'A canvas pavilion that pitches itself in minutes and holds the chill outside no matter the season.', Tier: 1, Effect: 'Camp always feels safe and comfortable, regardless of weather.' },
      { Id: 'ca-hearth', Name: 'Hearthstone', Description: 'A fist-sized stone that lights a fire from nothing and never needs fuel.', Tier: 1, Effect: 'Camp always has light and warmth, even with no wood to burn.' },
      { Id: 'ca-wardposts', Name: 'Warding Posts', Description: 'Four carved stakes that hum faintly when driven into the ground around a camp.', Tier: 2, Effect: 'Anything hostile approaching the camp perimeter announces itself — treat Keep Watch’s 6- result as a 7-9 instead.' },
    ],
    /** Ruleset-V0.5.md's "Villains and Enemies in Combat" section gives exactly one worked example
     *  — Grizza the Tall — complete with Goal, flavor text, and a Toughness/Status-Limits stat
     *  block; seeded here verbatim rather than invented. `Aspects`/`Scar`/`SkillTags`/`Resources`/
     *  `Powers`/`Attacks`/`Resistances`/`Vulnerabilities` fill in the doc's own "a Villain is
     *  comprised of" checklist from that same worked example's flavor text and the earlier Adventure
     *  Concept text ("a pack of goblins... steal the blacksmith's daughter... to cleanse the ancient
     *  tomb they've recently overtaken") — the doc doesn't spell every one of these fields out for
     *  Grizza by name, so this is a reasonable, clearly-attributed fill-in, not a second invented
     *  Villain. */
    villains: [
      {
        Id: 'vil-grizza',
        Name: 'Grizza the Tall',
        Aspects: ['Taller-Than-Average Goblin', 'Draped in Rotting Furs', 'Spider-Eyed Hat'],
        Goal: 'Prove her power to her new goblin clan and earn the family she never had, backed by a claimed connection to the divine Vuldec, Lord of Goblins.',
        Scar: 'Shunned by her own clan as a child, then watched its leaders turn even her friends against her — she has spent every day since proving she needs none of them.',
        SkillTags: ['Command Over Lesser Magic', 'Commands Fierce Loyalty', 'Never Forgets a Slight'],
        Resources: ['Her Goblin Clan', 'The Ancient Tomb They’ve Overtaken', 'Claimed Favor of Vuldec, Lord of Goblins', 'The Blacksmith’s Captive Daughter'],
        Powers: 'Commands lesser magic — enough to convince a clan of goblins that she truly speaks for Vuldec.',
        Attacks: 'Fall to my Power! — closes to Melee and lashes out, dealing Wounded and Wobbly. Fearsome Yell — a deafening roar that rattles everyone nearby, dealing Deafened to all who hear it.',
        Resistances: 'Fear and intimidation alone don’t rattle her — she’s used to being underestimated.',
        Vulnerabilities: 'Her connection to Vuldec is a bluff; exposing it in front of her clan strips her authority instantly.',
        Toughness: 'Medium',
        StatusLimits: [{ StatusName: 'Hurt', Limit: 12 }, { StatusName: 'Scared', Limit: 13 }, { StatusName: 'Tricked', Limit: 9 }],
      },
    ],
    /** Two illustrative NPCs pulled from the same Grizza/goblin-tomb material Ruleset-V0.5.md's
     *  worked example centers on — Rosa is the doc's own named Hook figure ("Rosa the Blacksmith
     *  barges into wherever the Heroes are, pleading for someone capable to travel into the woods
     *  and find where the goblins dragged off her daughter"); Skreel is invented to show a
     *  Combatant-NPC entry (Type: Minion, real Status Limits) alongside Rosa's non-Combatant one. */
    npcs: [
      { Id: 'npc-rosa', Name: 'Rosa the Blacksmith', Aspects: ['Soot-Stained Apron', 'Steady Hammer Hand', 'Won’t Stop Until Her Daughter’s Found'], Type: 'Ally', Goal: 'Get her daughter back from the goblins, whatever it takes.', HeroConnection: '', SkillTags: ['Forge and Repair', 'Knows Every Road Out of Town', 'Stubborn as the Anvil'], IsCombatant: false, StatusLimits: [{ StatusName: 'Overwhelmed', Limit: 2 }] },
      { Id: 'npc-skreel', Name: 'Skreel', Aspects: ['Notched Ear', 'Twitchy and Underfed', 'Carries Too Many Knives'], Type: 'Minion', Goal: 'Stay in Grizza’s good graces, and out of the way of her temper.', HeroConnection: '', SkillTags: ['Knows the Tomb’s Back Ways', 'Better at Running Than Fighting', 'Eavesdrops on Everyone'], IsCombatant: true, StatusLimits: [{ StatusName: 'Hurt', Limit: 6 }] },
    ],
    /** Three illustrative Locations, same Grizza/goblin-tomb material — one for each of the doc's
     *  own suggested starting points ("the general town or area, where the Villain resides, places
     *  where victims or witnesses... reside"). `CustomMoves` stays empty for all three — the doc's
     *  own "Optionally, one or more custom moves" is left unauthored rather than invented. */
    locations: [
      { Id: 'loc-hollow-bend', Name: 'Hollow Bend', Aspects: ['The Blacksmith’s Forge Still Burns', 'Rumors Travel Faster Than News', 'One Road In, One Road Out'], LocationType: 'Nexus', CustomMoves: '' },
      { Id: 'loc-sunken-tomb', Name: 'The Sunken Tomb', Aspects: ['Goblin Totems Line the Entrance', 'Ancient Wardstones, Half-Buried', 'The Air Smells of Old Blood'], LocationType: 'Lair', CustomMoves: '' },
      { Id: 'loc-whispering-wood', Name: 'The Whispering Wood', Aspects: ['Trails That Double Back on Themselves', 'Old Goblin Totems Nailed to Trees', 'Something Always Watching From the Dark'], LocationType: 'Wilds', CustomMoves: '' },
    ],
    settings: {
      Id: 'set-1',
      PotentialTrackLength: 5,
      RapportTrackLength: 5,
      BondTrackLength: 5,
      StatusMaxRank: 6,
      ConditionFloor: -3,
      RecoveriesMax: 6,
      GlossaryAutoLink: true,
    },
    loadTiers: [
      { Key: 'Light', Base: 3, Note: 'You move quickly, have +1 Speed in Combat, and are relatively inconspicuous.' },
      { Key: 'Normal', Base: 5, Note: 'You move normally and look like a prepared adventurer.' },
      { Key: 'Heavy', Base: 6, Note: 'You move slower than normal, have −1 Speed in Combat, and look like a particularly armed combatant.' },
    ],
  };
}
