import type { Improvement, ImprovementTree, Library } from './types.js';

/**
 * Content library seed data, ported verbatim from design/_shared/library.js.
 * Everything here is a *definition*; character sheets reference these by Id and never copy
 * them, so an admin-panel edit reaches every sheet on next render.
 */

/** The 25 Hero Improvement Trees (11 Combat + 14 Narrative), named and themed directly from
 *  Ruleset-V0.5.md's "Hero Improvements" section — real, authored content, unlike the
 *  placeholder nodes built on top of them below. "Command" is named twice in the doc (once per
 *  category) — kept as two distinct trees with the same display Name, disambiguated by Category,
 *  rather than merged into one. */
const IMPROVEMENT_TREE_DEFS: { id: string; name: string; category: 'Combat' | 'Narrative'; description: string }[] = [
  { id: 'it-strike', name: 'Strike', category: 'Combat', description: 'Direct attacks, signature weapons, and straightforward harm.' },
  { id: 'it-smash', name: 'Smash', category: 'Combat', description: 'Overwhelming force, wide destruction, and broken obstacles.' },
  { id: 'it-exploit', name: 'Exploit', category: 'Combat', description: 'Ambushes, marks, counters, and weak points.' },
  { id: 'it-control', name: 'Control', category: 'Combat', description: 'Restraint, forced movement, fear, terrain, and denial.' },
  { id: 'it-maneuver', name: 'Maneuver', category: 'Combat', description: 'Charges, retreats, leaps, flight, teleportation, and repositioning.' },
  { id: 'it-guard', name: 'Guard', category: 'Combat', description: 'Armor, shields, wards, parries, and interposition.' },
  { id: 'it-endure', name: 'Endure', category: 'Combat', description: 'Durability, resistance, recovery, and refusing defeat.' },
  { id: 'it-support', name: 'Support', category: 'Combat', description: 'Healing, cleansing, empowerment, and practical aid.' },
  { id: 'it-command-combat', name: 'Command', category: 'Combat', description: 'Formations, morale, coordination, and directing allies.' },
  { id: 'it-escalate', name: 'Escalate', category: 'Combat', description: 'Stances, reserves, sustained effects, and growing power.' },
  { id: 'it-transform-summon', name: 'Transform & Summon', category: 'Combat', description: 'Battle forms, manifestations, duplicates, and summons.' },
  { id: 'it-sneak', name: 'Sneak', category: 'Narrative', description: 'Concealment, infiltration, disguise, theft, escape, and sabotage.' },
  { id: 'it-traverse', name: 'Traverse', category: 'Narrative', description: 'Journeys, navigation, scouting, mounts, and obstacles.' },
  { id: 'it-sense', name: 'Sense', category: 'Narrative', description: 'Perception, tracking, investigation, divination, and danger.' },
  { id: 'it-study', name: 'Study', category: 'Narrative', description: 'Lore, research, memory, languages, analysis, and learning.' },
  { id: 'it-charm', name: 'Charm', category: 'Narrative', description: 'Persuasion, deception, intimidation, performance, and reputation.' },
  { id: 'it-command-narrative', name: 'Command', category: 'Narrative', description: 'Authority, followers, factions, crowds, and institutions.' },
  { id: 'it-bond', name: 'Bond', category: 'Narrative', description: 'Relationships, loyalty, companions, community, and trust.' },
  { id: 'it-tinker', name: 'Tinker', category: 'Narrative', description: 'Crafting, repair, alchemy, tools, gear, food, and creation.' },
  { id: 'it-excel', name: 'Excel', category: 'Narrative', description: 'Exceptional training, reliable competence, and mastery.' },
  { id: 'it-survive', name: 'Survive', category: 'Narrative', description: 'Rest, supplies, hazards, recovery, and self-sufficiency.' },
  { id: 'it-commit', name: 'Commit', category: 'Narrative', description: 'Oaths, duties, faith, quests, destiny, and redemption.' },
  { id: 'it-scheme', name: 'Scheme', category: 'Narrative', description: 'Plans, flashbacks, contacts, luck, wealth, and contingencies.' },
  { id: 'it-transform-narrative', name: 'Transform', category: 'Narrative', description: 'Changes of identity, form, supernatural nature, and apotheosis.' },
  { id: 'it-shape', name: 'Shape', category: 'Narrative', description: 'Rituals, utility magic, communion, conjuration, and reality.' },
];

const SEED_IMPROVEMENT_TREES: ImprovementTree[] = IMPROVEMENT_TREE_DEFS.map((t) => ({ Id: t.id, Name: t.name, Category: t.category, Description: t.description }));

/** Ruleset-V0.5.md names all 25 trees above but never authors a single node on any of them — no
 *  Starting Improvement, no prerequisite line, nothing (see HANDOFF.md open issue 12). Rather
 *  than invent real mechanical effects that don't exist in the source document, each tree gets
 *  exactly two clearly-labeled placeholder nodes (a Starting Improvement and one node chained to
 *  it) — enough to exercise the DAG gate (`improvementState` in `logic.ts`) and the admin
 *  validation (`validateImprovementDag` in `adminLogic.ts`) end to end. Replace these with real
 *  authored content once the repo owner writes it; nothing else in this slice depends on their
 *  Effect text being real. */
const PLACEHOLDER_IMPROVEMENT_EFFECT = 'Placeholder — Ruleset-V0.5.md names this tree but has not authored its Improvements yet. This node only exists to exercise the prerequisite DAG; replace with real content (see HANDOFF.md open issue 12).';

const SEED_IMPROVEMENTS: Improvement[] = IMPROVEMENT_TREE_DEFS.flatMap((t) => {
  const startId = `im-${t.id.slice(3)}-1`;
  const nextId = `im-${t.id.slice(3)}-2`;
  return [
    { Id: startId, TreeId: t.id, Name: `${t.name} I (Starting, placeholder)`, Effect: PLACEHOLDER_IMPROVEMENT_EFFECT, IsStarting: true, PrerequisiteIds: [] },
    { Id: nextId, TreeId: t.id, Name: `${t.name} II (placeholder)`, Effect: PLACEHOLDER_IMPROVEMENT_EFFECT, IsStarting: false, PrerequisiteIds: [startId] },
  ];
});

export function seedLibrary(): Library {
  return {
    virtues: [
      { Id: 'v-might', Name: 'Might', Tagline: 'Physicality & Force', Essence: 'Your raw power, athleticism, and physical capabilities.', UsageHelperText: 'To smash through a gate, wrestle a beast, or climb a mountain.' },
      { Id: 'v-mettle', Name: 'Mettle', Tagline: 'Willpower & Grit', Essence: 'Your internal fire, your bravery in the face of the unknown, and your spiritual resilience.', UsageHelperText: 'To stare down a dragon’s gaze, resist the temptation of a cursed relic, or keep moving when your legs want to give out.' },
      { Id: 'v-heart', Name: 'Heart', Tagline: 'Bond & Empathy', Essence: 'Your ability to connect with others, to inspire hope, and to act on your deepest convictions.', UsageHelperText: 'To convince a village to stand and fight, comfort a grieving companion, or sacrifice your own safety for the group’s sake.' },
      { Id: 'v-wit', Name: 'Wit', Tagline: 'Perception & Instinct', Essence: 'Your sharpness of mind, your ability to read a room, and your eye for the hidden or the mysterious.', UsageHelperText: 'To find the hidden latch in a ruin, realize an NPC is hiding a secret, or notice the ambush before the arrows fly.' },
      { Id: 'v-guile', Name: 'Guile', Tagline: 'Strategy & Subtlety', Essence: 'Your cleverness, your dexterity, and your ability to outmaneuver or outthink an opponent.', UsageHelperText: 'To sneak past a sentry, pick a complex lock, set a clever trap, or misdirect a foe’s attention during a tense parley.' },
    ],
    conditions: [
      { Id: 'c-exhausted', Name: 'Exhausted', VirtueId: 'v-might', RollPenalty: -2, ClearAction: 'Recover from your exhaustion by indulging in a vice and shirking responsibility.' },
      { Id: 'c-afraid', Name: 'Afraid', VirtueId: 'v-mettle', RollPenalty: -2, ClearAction: 'Come down from your fear by running away from something challenging.' },
      { Id: 'c-hopeless', Name: 'Hopeless', VirtueId: 'v-heart', RollPenalty: -2, ClearAction: 'Absolve your guilt by punishing yourself, or blame a party member related to your guilt.' },
      { Id: 'c-irrational', Name: 'Irrational', VirtueId: 'v-wit', RollPenalty: -2, ClearAction: 'Vent your anger by hurting someone important to you, or damage something important.' },
      { Id: 'c-distracted', Name: 'Distracted', VirtueId: 'v-guile', RollPenalty: -2, ClearAction: 'Get over your insecurity by making a rash action without discussing it with the party.' },
    ],
    armorTypes: [
      { Id: 'a-physical', Name: 'Physical', Key: 'Physical', Description: 'Mundane protection — plate, hide, a shield taken on the arm.' },
      { Id: 'a-heavy', Name: 'Heavy', Key: 'Heavy', Description: 'Bulk that turns a blow aside entirely.' },
      { Id: 'a-special', Name: 'Special', Key: 'Special', Description: 'Warded, blessed, or otherwise uncanny protection.' },
    ],
    items: [
      { Id: 'i-sword', Name: 'Arming sword', LoadCost: 1, Description: 'A soldier’s blade, well balanced and unremarkable.' },
      { Id: 'i-shield', Name: 'Kite shield', LoadCost: 1, GrantsArmorTypeId: 'a-physical', Description: 'Battered oak faced in hide.' },
      { Id: 'i-mail', Name: 'Coat of mail', LoadCost: 2, GrantsArmorTypeId: 'a-heavy', Description: 'Heavy, loud, and worth every pound.' },
      { Id: 'i-bootknife', Name: 'Boot knife', LoadCost: 0, Description: 'Small enough that nobody counts it.' },
      { Id: 'i-rope', Name: 'Coil of rope', LoadCost: 1, Description: 'Fifty feet, hemp, slightly damp.' },
      { Id: 'i-lantern', Name: 'Hooded lantern', LoadCost: 1, Charges: 3, Description: 'Burns oil. Shutter it to hide the light.' },
      { Id: 'i-poultice', Name: 'Field poultices', LoadCost: 0, Charges: 3, Description: 'Spend a charge to clear a Rank of a physical Status.' },
      { Id: 'i-wardstone', Name: 'Ward-stone', LoadCost: 0, Charges: 1, GrantsArmorTypeId: 'a-special', Description: 'Cracks when it saves you. Once.' },
      { Id: 'i-rations', Name: 'Trail rations', LoadCost: 1, Description: 'A week of unpleasant but sufficient food.' },
      { Id: 'i-toolkit', Name: 'Thief’s tools', LoadCost: 0, Charges: 2, Description: 'Picks, wedges, a mirror on a wire.' },
      { Id: 'i-banner', Name: 'House banner', LoadCost: 2, Description: 'Impossible to conceal. That is the point.' },
    ],
    motifs: [
      { Id: 'mo-artisan', Name: 'Artisan', Description: 'You are skilled in a grounded craft or lifelong trade, honed through quiet dedication and practice', SkillTagExamples: ['Armorer', 'Artificer', 'Baker', 'Blacksmith', 'Bowyer and Fletcher', 'Brewer of Potent Spirits', 'Camp Cook', 'Carpenter', 'Cunning Trapmaker', 'Field Medic', 'Inventor', 'Jeweler', 'Leatherworker', 'Locksmith', 'Meticulous Mapmaker', 'Ol’ Stablemaster', 'Reliable Wagonwright', 'Ropemaker and Rigger', 'Seasoned Shipwright', 'Stonemason', 'Tailor', 'Tinker', 'Traveling Apothecary', 'Undertaker’s Trade'], FlawTagExamples: ['A Perfectionist at Heart', 'Always Taking Commissions', 'Can’t Leave It Broken', 'Covered in Grime', 'Dangerous Prototype', 'Debts to the Guild', 'Distracted by Fine Craftsmanship', 'Expensive Materials', 'Fingers Stiff with Age', 'I Know Better Than the Customer', 'My Finest Work Was Stolen', 'Never Enough Time', 'No Proper Workshop', 'Protective of My Tools', 'Rival Artisan', 'The Work Comes First', 'Won’t Use Shoddy Materials'] },
      { Id: 'mo-bearer', Name: 'Bearer', Description: 'You carry a relic of profound power, it has a legacy of magic, mystery, or myth.', SkillTagExamples: ['Alchemist’s Satchel', 'Ancestral Bow', 'Arcane Grimoire', 'Boots That Know the Road', 'Bow of the Moon Hunt', 'Bronze Compass', 'Clockwork Companion', 'Cloak of a Thousand Faces', 'Crown Without a Kingdom', 'Cursed Weapon', 'Dragon Egg', 'Ember of the First Flame', 'Enchanted Armor', 'Flying Carpet', 'Giant’s Iron Gauntlet', 'Holy Relic', 'Horn of the Herd', 'Living Shield', 'Magic Sword', 'Magical Map', 'Mask of the Nameless Saint', 'Master Key', 'Masterwork Thieves’ Tools', 'Mysterious Circlet', 'Ring of Royal Command', 'Seed of the World-Tree', 'Shield of the Last Guardian', 'Spirit Lantern', 'Trickster’s Mask', 'Wizard’s Staff'], FlawTagExamples: ['Coveted by Powerful Enemies', 'Cursed to Keep It Close', 'Draws Unwanted Attention', 'Everyone Thinks It Belongs to Them', 'It Awakens at the Worst Time', 'It Cannot Be Replaced', 'It Remembers Previous Owners', 'It Whispers Temptations', 'Its Power Has a Price', 'Magic Leaves a Trail', 'Must Keep It Secret', 'My Claim Is Questioned', 'Not Yet Worthy', 'Others Suffer When I Use It', 'Protective to a Fault', 'Requires Rare Offerings', 'The Relic Has a Will of Its Own', 'The Relic Is Failing', 'Too Dangerous to Surrender', 'Wanted by Its Creator'] },
      { Id: 'mo-devoted', Name: 'Devoted', Description: 'You have an unshakable loyalty to a cause, creed, or companion.', SkillTagExamples: ['A Light Against Darkness', 'Animal Companion', 'Bodyguard', 'Caregiver', 'Carry Their Memory', 'Compassionate', 'Defender of the Old Ways', 'Dependable', 'Family First', 'Feed the Hungry', 'Friend to All', 'Friend to Every Beast', 'Guardian of Our Village', 'Helpful', 'Hope in Hopeless Places', 'Loyal Companion', 'Mentor', 'Mercy Before Vengeance', 'My Companion Comes First', 'No One Left Behind', 'Patriot', 'Protective', 'Selfless', 'Servant of the Sacred Flame', 'Shield of the Innocent', 'Stand With the Outcast', 'The Cause Above Comfort', 'The Crew Is My Family', 'True Believer', 'Trustworthy', 'Voice of the Common Folk'], FlawTagExamples: ['Can’t Abandon Those in Need', 'Compassion for the Enemy', 'Easily Exploited Loyalty', 'Family Before the Quest', 'Forgives Too Easily', 'I Promised I’d Return', 'My Charge Cannot Protect Themself', 'No One Left Behind', 'Others Depend on Me', 'Refuses a Necessary Sacrifice', 'Someone Always Needs Help', 'Takes the Blame for Companions', 'Their Pain Is Mine', 'Trusts the Wrong People', 'Unable to Say No', 'What If the Cause Is Wrong?', 'Will Not Break a Confidence', 'Won’t Endanger Innocents', 'Won’t Leave the Dead Unburied'] },
      { Id: 'mo-exalted', Name: 'Exalted/Lowly', Description: 'Your rank, reputation, and influence within the intricate webs of society.', SkillTagExamples: ['Arena Champion', 'Beggar', 'Beloved Folk Hero', 'Commoner', 'Courtier', 'Debt-Bound Peasant', 'Decorated Captain', 'Disgraced Knight', 'Disgraced Noble', 'Famous Entertainer', 'Feared Crime Boss', 'Foreign Ambassador', 'Fugitive', 'High Priestess', 'Infamous Outlaw', 'Landed Noble', 'Merchant', 'Pirate Captain', 'Politician', 'Respected Guildmaster', 'Royal Advisor', 'Royal in Exile', 'Royal Spymaster', 'Servant', 'Street Urchin', 'Tavern Keeper', 'Village Elder'], FlawTagExamples: ['A Reputation to Maintain', 'Always Recognized', 'An Embarrassment to My Station', 'Beneath Their Notice', 'Bound by Courtly Etiquette', 'Class Resentment', 'Debts Above My Means', 'Expected to Lead', 'Family Scandal', 'Hated by the Common Folk', 'I Have No Authority Here', 'Mistaken for a Servant', 'My Title Opens the Wrong Doors', 'Old Rivals at Court', 'Orders from Above', 'People Want Favors', 'Poor and Proud', 'Privilege Blinds Me', 'The Law Watches Me'] },
      { Id: 'mo-exemplar', Name: 'Exemplar', Description: 'You have a defining temperament or worldview. Or perhaps some specific physical, mental, or emotional qualities.', SkillTagExamples: ['Affable', 'Always Has a Plan', 'Ambitious', 'Battle-Hardened', 'Bookworm', 'Born Leader', 'Built to Endure', 'Charming', 'Coldly Logical', 'Cowardly', 'Curious to a Fault', 'Disciplined', 'Fearless in the Face of Danger', 'Hands Quicker Than Thought', 'Heart of Gold', 'Hot-Headed', 'Intimidating Presence', 'Iron Stomach', 'Jovial Spirit', 'Keen-Eyed', 'Light on My Feet', 'Lone Wolf', 'Never Forgets a Face', 'Practiced Liar', 'Prankster', 'Quick Study', 'Reckless', 'Silver-Tongued', 'Stubborn as Stone', 'Survivor', 'Unshakably Calm', 'Young and Naive'], FlawTagExamples: ['Always Has to Be Right', 'Can’t Resist a Dare', 'Coward at Heart', 'Craves Attention', 'Easily Flattered', 'Envious of the Gifted', 'Falls for a Pretty Face', 'Holds a Grudge', 'Jumps to Conclusions', 'Laughs at the Wrong Time', 'Never Asks for Help', 'No Patience for Fools', 'Overconfident', 'Painfully Honest', 'Quick to Anger', 'Reckless Curiosity', 'Too Proud to Retreat', 'Trusts Too Easily', 'Vindictive When Crossed', 'Won’t Admit Fear'] },
      { Id: 'mo-fated', Name: 'Fated', Description: 'You walk a prophesied path, divine calling, or inexorable fate.', SkillTagExamples: ['Born Beneath the Red Comet', 'Chosen by a Forgotten God', 'Death Must Wait', 'Doom Follows in My Wake', 'Doomed Hero', 'Dragon Slayer', 'Face My Own Blood', 'Fated Rival', 'Fated to Unite the Realms', 'Fortune Favors the Bold', 'Future Monarch', 'Harbinger', 'Last Hope of My House', 'Last of My Kind', 'Lost Heir', 'Marked by the Gods', 'Marked by Prophecy', 'Miracle Child', 'Promise Across Lifetimes', 'Prophetic Dreamer', 'Reincarnated Hero', 'Sacrificial Hero', 'Survivor Against the Odds', 'The Lost City Calls to Me', 'The Stars Point the Way', 'Unwilling Savior'], FlawTagExamples: ['A Doomed Bloodline', 'Destiny Demands Sacrifice', 'Dreams Reveal Too Much', 'Fate Threatens Those I Love', 'Fear of Becoming the Villain', 'Mistaken for the Chosen One', 'My Destiny Comes Before Everything', 'My Rival Shares My Fate', 'Omens Distract Me', 'Others Want to Control My Destiny', 'Prophecy Is Ambiguous', 'The Future Is Changing', 'The Gods Keep Testing Me', 'The Wrong People Believe in Me', 'Those Who Know the Prophecy Hunt Me', 'What If the Prophecy Is Wrong?'] },
      { Id: 'mo-forged', Name: 'Forged', Description: 'You have been defined by some crucible of your past; a defining trauma, triumph, or event that shaped you.', SkillTagExamples: ['Abandoned Child', 'Betrayed by My Own', 'Cult Survivor', 'Disgraced Soldier', 'Dragon Attack Survivor', 'Escaped the Gallows', 'Exiled for the Truth', 'Fallen Noble', 'Forged in War', 'Former Criminal', 'Former Cultist', 'Fugitive', 'Grew Up on the Streets', 'Nothing Left to Lose', 'Orphan', 'Outcast', 'Plague Survivor', 'Prisoner of War', 'Raised by Monsters', 'Raised in Chains', 'Runaway', 'Scarred', 'Scavenger', 'Shipwreck Survivor', 'Siege Survivor', 'Sole Survivor', 'Trained From Childhood', 'Veteran of the Fighting Pits'], FlawTagExamples: ['Afraid It Will Happen Again', 'Betrayed Once and Trust No One', 'Can’t Forgive Myself', 'Chronic Old Wound', 'Enemies from My Past', 'Flinches at the Reminder', 'Former Master Wants Me Back', 'Hunted for What I Did', 'I Left Someone Behind', 'Nightmares', 'No Mercy for People Like Them', 'Old Habits Die Hard', 'Someone Knows the Truth', 'Survivor’s Guilt', 'The Past Hardened Me', 'Trouble Brings Out the Old Me', 'Unable to Return Home', 'Vengeance Before Duty', 'Won’t Be Helpless Again'] },
      { Id: 'mo-inheritor', Name: 'Inheritor', Description: 'You are greatly affected by the bloodline, culture, and traditions of the people you call your own.', SkillTagExamples: ['Blood of Giant Slayers', 'Child of Two Peoples', 'Court-Bred Scion', 'Descendant of the Old Empire', 'Desert Caravan Folk', 'Desert Nomad', 'Dwarven Stone-Sense', 'Family of Famous Thieves', 'Forest Clan', 'Guildborn and Raised', 'Heir to the Witch-Queens', 'Highlander', 'Horse-Lord', 'It Takes a Village', 'Keeper of Ancestor Songs', 'Last Speaker of the Old Tongue', 'Mountain Clan Hospitality', 'Noble', 'Nomad of the Painted Steppe', 'Pirate Kin', 'Raised by Riverfolk', 'Royal Education', 'Sacred Grove Traditions', 'Salt-Coast Tradition', 'Seafaring People', 'Street-Raised', 'Temple-Raised', 'Under-City Born', 'Warrior Culture', 'World Traveler'], FlawTagExamples: ['Ancestral Feud', 'Bound by Old Customs', 'Clan Before Companions', 'Exiled for my Choices', 'Expected to Marry Well', 'Family Name Opens Old Wounds', 'Foreign Ways Confuse Me', 'Heirloom Obligations', 'I Must Prove My Heritage', 'Inherited Enemies', 'Last to Carry the Tradition', 'My People Need Me', 'Never Fully Accepted', 'Old Prejudices', 'Outsider to Both Worlds', 'Relatives Everywhere', 'Sacred Taboos', 'The Ancestors Are Watching', 'Tradition Forbids It', 'Unwanted Inheritance', 'What Will My People Think?'] },
      { Id: 'mo-mystic', Name: 'Mystic', Description: 'You wield an ability with the unseen or supernatural forces that shape the world.', SkillTagExamples: ['Aura Reader', 'Cleric', 'Curse Breaker', 'Diviner', 'Dreamwalker', 'Druid', 'Elementalist', 'Enchanter', 'Guided by the Stars', 'Hands of Healing Light', 'Hedge Mage', 'Keeper of Wards', 'Listener at the Grave', 'Moon-Touched Illusionist', 'Necromancer', 'Ritualist', 'Rune Speaker', 'Shaman', 'Sorcerer', 'Spellblade', 'Spirit Medium', 'Storm Whisperer', 'Summoner', 'Warlock', 'Wild Magic Channeler', 'Witch', 'Wizard'], FlawTagExamples: ['Can’t Ignore the Arcane', 'Casting Attracts Attention', 'Curious About Forbidden Magic', 'Emotions Unleash My Power', 'Haunted by Spirits', 'Hunters on My Trail', 'Magic Falters Before Cold Iron', 'Must Speak the Incantation', 'Power Hungers for More', 'Rituals Take Too Long', 'Rival Knows My Secrets', 'Spells Leave a Mark', 'Tempted by Easy Power', 'The Unseen Speak Constantly', 'Uncontrolled Visions', 'Vulnerable While Casting', 'Wards I Cannot Cross', 'What Answers Me Isn’t Friendly', 'Wrong Phase of the Moon'] },
      { Id: 'mo-mythic', Name: 'Mythic', Description: 'You are a creature of magic or myth.', SkillTagExamples: ['Angel-Spawn', 'Beastfolk', 'Born of Living Stone', 'Centaur', 'Child of the Deep', 'Clockwork Soul', 'Disembodied Spirit', 'Dragonkin', 'Dryad of the Wandering Grove', 'Dwarf', 'Elf', 'Fair Folk Glamour', 'Fairy', 'Giantkin Might', 'Goblin', 'Gorgon’s Gaze', 'Hearthfolk', 'Hellspawn', 'Living Construct', 'Living Shadow', 'Merfolk', 'Minotaur', 'Moon-Cursed Werebeast', 'Orc', 'Revenant’s Tenacity', 'Shapeshifter', 'Troll-Blooded Regeneration', 'Vampire', 'Voice of the Sphinx', 'Wings of the Harpy'], FlawTagExamples: ['Bound by Ancient Rules', 'Cannot Pass for Mortal', 'Cannot Tell a Direct Lie', 'Creature of Old Hungers', 'Feared on Sight', 'Holy Ground Rejects Me', 'Hunters Track My Kind', 'Instinct Over Reason', 'Iron Burns Me', 'Magic Reveals What I Am', 'My True Form Is Dangerous', 'Natural Enemies Know My Scent', 'No Place Among Mortals', 'Old Stories Get Me Wrong', 'Parts of Me Are Valuable', 'Prone to Transformation', 'Strange Customs', 'The Wild Calls Me Home', 'True Name Holds Power', 'Unnatural Appetite'] },
      { Id: 'mo-sage', Name: 'Sage', Description: 'You carry rare or secret knowledge. Perhaps due to arcane or divine insight, or specialized schooling.', SkillTagExamples: ['Alchemical Theorist', 'Ancient Historian', 'Appraiser', 'Archaeologist', 'Archivist of Prophecy', 'Cartographer of Lost Roads', 'Curator of Curses', 'Doctor', 'Genealogist of Great Houses', 'Herbalist of the Wilds', 'Investigator', 'Librarian', 'Magical Historian', 'Monster Lore', 'Occult Researcher', 'Planar Cosmologist', 'Religious Scholar', 'Scholar', 'Scholar of Forbidden Magic', 'Scribe', 'Student of the Heavens', 'Translator'], FlawTagExamples: ['Can’t Leave a Mystery Unsolved', 'Dangerously Curious', 'Forbidden Knowledge Tempts Me', 'Forgets Practical Matters', 'Knowledge Others Would Kill For', 'Must Consult the Texts', 'Needs Better Evidence', 'No Field Experience', 'Overcomplicates Everything', 'Poor Under Pressure', 'Research Takes Time', 'Rival Scholar', 'Speaks in Unhelpful Jargon', 'Theory Before Common Sense', 'Trusts the Written Word Too Much', 'Unable to Admit Ignorance'] },
      { Id: 'mo-sworn', Name: 'Sworn', Description: 'You’ve sworn a solemn oath, sacred mission, or heavy mantle.', SkillTagExamples: ['Avenge the Fallen', 'Bounty Hunter', 'Break Every Chain', 'Bring Them Back Alive', 'Carry the Message', 'Crown’s Champion', 'Defend Sacred Ground', 'Demon Hunter', 'Finish What I Begin', 'Inquisitor', 'Keeper of Secrets', 'Lawkeeper', 'Monster Hunter', 'Never Draw First Blood', 'Never Refuse a Worthy Challenge', 'Oath of Allegiance', 'Paladin', 'Pay Every Debt', 'Protect the Heir', 'Questing Knight', 'Reclaim My Family’s Honor', 'Relic Seeker', 'Return the Stolen Crown', 'Royal Guard', 'Sacred Warden', 'Slay the Deathless King', 'Speak No Lies', 'Sworn Sword', 'Witch Hunter'], FlawTagExamples: ['Bound to an Unworthy Master', 'Cannot Break My Word', 'Cannot Turn Away from My Sworn Enemy', 'Duty Before Friendship', 'Failure Means Disgrace', 'I Must Answer Every Challenge', 'Must Bring Them Back Alive', 'My Oath Forbids the Easy Path', 'No Mercy for Oathbreakers', 'No Rest On My Quest', 'Orders Conflict with Conscience', 'Promises Keep Accumulating', 'Protect the Heir at Any Cost', 'Refuses Dishonorable Tactics', 'The Target May Be Innocent', 'Vengeance Clouds My Judgment'] },
      { Id: 'mo-virtuoso', Name: 'Virtuoso', Description: 'You display a breathtaking raw talent, hard-won skill, or impressive mastery.', SkillTagExamples: ['Assassin', 'Battlefield Tactician', 'Berserker', 'Blade Dancer', 'Circus Performer', 'Con Artist', 'Daring Acrobat', 'Deadeye Archer', 'Enthralling Orator', 'Escape Artist', 'Fancy Footwork', 'Fearless Beast Rider', '“Legendary” Gambler', 'Martial Artist', 'Master Lockpick', 'Master of Disguise', 'Master of Tongues', 'Navigator', 'Peerless Duelist', 'Ranger', 'Rooftop Runner', 'Seasoned Monster Hunter', 'Silver-Voiced Bard', 'Sleight-of-Hand Artist', 'Swashbuckler', 'Thief', 'Uncanny Tracker', 'Weaponmaster'], FlawTagExamples: ['A Rival Wants My Title', 'Always Showing Off', 'Can’t Resist a Challenge', 'Competition Brings Out My Worst', 'Everyone Expects Perfection', 'Has a Tell', 'Jealous of Greater Talent', 'Must Practice Constantly', 'No Patience for Amateurs', 'Overconfident in My Specialty', 'Pride Before Caution', 'Recognized by My Style', 'Requires Specialized Equipment', 'The Audience Matters Too Much', 'The Show Must Go On', 'Too Clever by Half', 'Tries the Impossible', 'Weak Outside My Specialty'] },
    ],
    improvementTrees: SEED_IMPROVEMENT_TREES,
    improvements: SEED_IMPROVEMENTS,
    moves: [
      { Id: 'm-defiant', Name: 'Stand Defiant', Kind: 'Basic', VirtueId: 'v-mettle', Description: 'When you weather an assault on the mind, body, or spirit, try to resist the urge to flee, or endure excruciating agony to hold your ground and try to stand defiant against it, roll +Mettle.', Results: { Tier3: { Description: 'You are unshakeable. You shrug off the pressure and gain a momentary advantage — take +1 forward against the source of the threat.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'You hold firm, but the effort costs you. Choose one:', ChooseCount: 1, Options: ['You feel shaken from the conflict; mark a Condition.', 'You don’t come out unscathed. Take two Strain, no Resist.', 'To push through costs you. Make a sacrifice to do it — name what that is and the GM will tell you if it is enough.'] }, Tier1: { Description: 'The pressure breaks you. You flinch, flee, or collapse, and the GM makes a hard move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-solace', Name: 'Offer Solace', Kind: 'Basic', VirtueId: 'v-heart', Description: 'When you try to comfort or support a Hero by offering solace and speaking from the heart, roll +Heart.', Results: { Tier3: { Description: 'If they open up to you, they either mark Potential on any Motif or clear a Condition. Additionally, mark a Bond with them.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'If they open up to you, they either mark Potential on any Motif, clear a Condition, or mark a Bond with you.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'Your approach was completely wrong. Mark a Condition or lose one Bond with them.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-sway', Name: 'Sway the Spirit', Kind: 'Basic', VirtueId: 'v-heart', Description: 'When trying to sway the spirit by using empathy, honesty, or comfort to get someone to do what you want, roll +Heart.', Results: { Tier3: { Description: 'They do as you ask to the best of their ability. If you’ve asked too much, they’ll tell you what it would take for them to do it.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They are willing, but the GM will choose one:', ChooseCount: 1, Options: ['You owe them a promise, a payment, or a favor in return. The more you ask, the more they’ll ask in return — they may demand it upfront.', 'They only follow through on a portion of your request, or will only do it after revealing a hard truth to you.', 'The act or their answer puts them in danger; take −1 forward due to the friction.'] }, Tier1: { Description: 'You reveal a vulnerability or offend them. If they choose to do what you ask, the favor you must do for them is particularly costly, challenging, or undignified. In any situation, the GM makes a Hard Move.', Options: [], ChooseCount: 0 } }, PlayerVariantResults: { Tier3: { Description: 'If they do what you ask, they mark Potential on any Motif or mark Bond between you. Then they get +1 forward.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'If they do what you ask, they mark Potential on any Motif or mark a Bond between you.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'It’s up to that player to decide how badly you offend or annoy them. Remove one Bond between you. They mark Potential on any Motif if they do not do what you asked.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-truth', Name: 'Discern the Truth', Kind: 'Basic', VirtueId: null, Description: 'When trying to discern the truth by scrutinizing someone in a probing conversation, roll +Wit. When observing someone in a moment of vulnerability, roll +Heart.', Results: { Tier3: { Description: 'Hold 2. While interacting with them, spend your hold 1-for-1 to ask a question to either the GM or player; they must answer truthfully.', ChooseCount: 0, Options: ['Are they telling the truth about ______?', 'What are they truly feeling?', 'What are their intentions?', 'What do they wish I would do?', 'How could I get them to ______?', 'What do they desire or fear?'] }, Tier2: { Description: 'Hold 1. While interacting with them, spend your hold 1-for-1 to ask a question to either the GM or player; they must answer truthfully.', ChooseCount: 0, Options: [] }, Tier1: { Description: 'You misread them completely, believing a complete untruth, or your pursuits reveal something important to your enemies. The GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } }, HoldGrant: { Tier3: 2, Tier2: 1 } },
      { Id: 'm-assess', Name: 'Assess the Situation', Kind: 'Basic', VirtueId: 'v-wit', Description: 'When you assess the situation to figure out what is going on in a moment of risk or conflict, roll +Wit. If no risk or conflict is present, say how you do it to ask the GM any question.', Results: { Tier3: { Description: 'Hold 3. Take +1 ongoing while acting on any answers.', ChooseCount: 0, Options: ['What here is concealed by magical or mundane means?', 'What’s my best way out, in, or through?', 'What here can I use to ______?', 'Who or what here is the greatest threat, or is in the greatest danger?', 'What is the true nature of ______?', 'How can we best end this quickly?'] }, Tier2: { Description: 'Hold 1, or hold 2 and choose one complication. Take +1 ongoing while acting on any answers.', ChooseCount: 1, Options: ['You find your answers the hard way. Mark a Condition.', 'What you find out puts you in imminent danger; the GM will say how after you choose this.', 'There’s a complication either with what you find or how you find it. Take two Strain, no Resist.', 'You reveal something to your enemies by leaving something behind or other means.', 'Your investigation draws immediate and unwanted attention.'] }, Tier1: { Description: 'You find your answer, but it is the worst possible news. The GM takes or holds a hard move.', Options: [], ChooseCount: 0 } }, HoldGrant: { Tier3: 3, Tier2: 1 } },
      { Id: 'm-past', Name: 'Consult the Past', Kind: 'Basic', VirtueId: 'v-wit', Description: 'When you search your memory for lore, history, or professional knowledge regarding a subject, consult the past. State how you might know this and roll +Wit. If you have access to a book or similar record of this info, add a relevant Boon.', Results: { Tier3: { Description: 'The GM will either tell you the detailed, useful truth or consult you on it, deciding on a truth together. You and any allies you brief take +1 Ongoing while you act on this knowledge and gain the Prepared Boon.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'The GM may tell you a vague or incomplete truth, or consult you on the truth your Hero thinks they know (but isn’t entirely correct). The information may reveal a new complication or danger. You and any allies you brief take +1 Forward while you act on this knowledge and gain the Prepared Boon.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'The answer reveals how bad things really are, or a danger you’re barreling toward. The GM makes a hard move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-lead', Name: 'Follow a Lead', Kind: 'Basic', VirtueId: 'v-guile', Description: 'When you try to find something or someone, follow a lead by asking around, tracking a trail, or opening up your senses, roll +Guile. If you are following a lead by gathering rumors and information, you may spend 1 Wealth to roll with Advantage.', Results: { Tier3: { Description: 'Choose one below. Then, you find them or it. You may ask one follow-up question about the destination or the journey.', ChooseCount: 1, Options: ['The search has many obstacles and detours. All Heroes in pursuit mark a Condition or take two Strain, no Resist, that carries into the next scene.', 'You’ve been noticed. It may be by your quarry or by someone or something else.', 'You’ve been held up. Some significant obstacle now stands in your way. Deal with that before continuing on to your quarry.', 'Your pursuit has you reveal information or a vulnerability to your quarry or their allies you’d rather they not have.', 'It takes too much time. The GM advances the Countdown or a Threat Clock moves to its next stage.', 'It reveals something that complicates your mission. The GM reveals an unwelcome truth that undermines your current goal.'] }, Tier2: { Description: 'Choose two below. Then, you find them or it.', ChooseCount: 2, Options: ['The search has many obstacles and detours. All Heroes in pursuit mark a Condition or take two Strain, no Resist, that carries into the next scene.', 'You’ve been noticed. It may be by your quarry or by someone or something else.', 'You’ve been held up. Some significant obstacle now stands in your way. Deal with that before continuing on to your quarry.', 'Your pursuit has you reveal information or a vulnerability to your quarry or their allies you’d rather they not have.', 'It takes too much time. The GM advances the Countdown or a Threat Clock moves to its next stage.', 'It reveals something that complicates your mission. The GM reveals an unwelcome truth that undermines your current goal.'] }, Tier1: { Description: 'You find what you’re looking for, but at great cost. Choose three below. The GM then makes a hard move.', ChooseCount: 3, Options: ['The search has many obstacles and detours. All Heroes in pursuit mark a Condition or take two Strain, no Resist, that carries into the next scene.', 'You’ve been noticed. It may be by your quarry or by someone or something else.', 'You’ve been held up. Some significant obstacle now stands in your way. Deal with that before continuing on to your quarry.', 'Your pursuit has you reveal information or a vulnerability to your quarry or their allies you’d rather they not have.', 'It takes too much time. The GM advances the Countdown or a Threat Clock moves to its next stage.', 'It reveals something that complicates your mission. The GM reveals an unwelcome truth that undermines your current goal.'] } } },
      { Id: 'm-expertise', Name: 'Invoke Expertise', Kind: 'Basic', VirtueId: null, Description: 'When you attempt to overcome an obstacle or take out enemies not worth Combat using a relevant Skill Tag, say your goal and roll + an appropriate Virtue. The GM will tell you if what you are trying to do can’t be accomplished. When you try to Invoke Expertise without having a related Skill, you Take a Risk.', Results: { Tier3: { Description: 'You do what you intended; describe what it looks like.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'Your actions leave you vulnerable, you do what you intended but must choose one consequence:', ChooseCount: 1, Options: ['Burdened. You receive a worse outcome, hard choice, or price to pay.', 'Compromised. The situation escalates; you run out of the frying pan and into the fire.', 'Delayed. You take too long; the situation around you changes in a meaningful way.', 'Depleted. Expend a resource or break a useful item.', 'Exposed. Draw unwanted attention or leave a traceable trail.'] }, Tier1: { Description: 'Your skills and training aren’t enough here. The GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-risk', Name: 'Take a Risk', Kind: 'Basic', VirtueId: null, Description: 'When you attempt to overcome an obstacle or take out enemies not worth Combat without a relevant Skill Tag, say your goal and roll + an appropriate Virtue. The GM will tell you if what you are trying to do can’t be accomplished. A catch-all move for anything you don’t have Skill Tags in — use it as a last resort; if any other move is more specific, use that.', Results: { Tier3: { Description: 'You achieve your goal but at a cost; choose one consequence.', ChooseCount: 1, Options: ['Burdened. You receive a worse outcome, hard choice, or price to pay.', 'Compromised. The situation escalates; you run out of the frying pan and into the fire.', 'Delayed. You take too long; the situation around you changes in a meaningful way.', 'Depleted. Expend a resource or break a useful item.', 'Exposed. Draw unwanted attention or leave a traceable trail.'] }, Tier2: { Description: 'You achieve your goal, but things get messy. The GM chooses one consequence.', ChooseCount: 1, Options: ['Burdened. You receive a worse outcome, hard choice, or price to pay.', 'Compromised. The situation escalates; you run out of the frying pan and into the fire.', 'Delayed. You take too long; the situation around you changes in a meaningful way.', 'Depleted. Expend a resource or break a useful item.', 'Exposed. Draw unwanted attention or leave a traceable trail.'] }, Tier1: { Description: 'Things go south. The GM takes or holds a Hard Move.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-push', Name: 'Push Yourself', Kind: 'Adventure', VirtueId: null, Description: 'During the game, when one of your Skill Tags applies to any roll you are about to make, you can use that tag to demonstrate your proficiency. Before rolling you can declare your Skill Tag to add its +1 to the roll. If more than one of your Skill Tags applies, you may Push Yourself — mark one Condition and add an additional +1 to your roll.', Results: { Tier3: { Description: 'No roll of its own — a modifier on whatever roll you apply it to.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-camp', Name: 'Make Camp', Kind: 'Adventure', VirtueId: null, Description: 'While on an Adventure, when you are in a place of relative safety and decide to spend time together to rest or unwind, Make Camp — a few hours, a night, or a few days. While at Camp, all party members have +1 Ongoing to all +Heart rolls. First, the GM advances the Adventure’s Countdown — once immediately, then again for every full day that dawns at this Camp (either the Countdown or another Threat’s Clock, and they may decline to say what changed). Then, if anyone has at least 5 Potential on a Motif, any two Heroes have at least 5 Bond, or the Party has at least 5 Rapport, you may Advance a Motif, Progress the Party, or Forge a Bond — more than once if you have enough. All party members then clear one Condition, Recuperate, and refresh all Armor. Each player can then take as many Camp Actions as Party Level + 1. Afterward, if your Camp is somewhere potentially dangerous or vulnerable, the Party can decide to Keep Watch before heading out.', Results: { Tier3: { Description: 'No roll. Camp always works — the question is what it costs you in time.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-session', Name: 'End the Session', Kind: 'Adventure', VirtueId: null, Description: 'When you finish a session, complete the following steps to reflect on your progress. As a group, answer: Did we uncover something new about the world? Did we stop a dangerous threat or save someone from certain doom? Did we learn something new about each other, or were we particularly cooperative? Did we defeat a Villain or important enemy? Did we move to accomplish our Party Quest? If 1-2 answers are yes, mark 1 Rapport; if 3+ are yes, mark 2 Rapport. Next, each player chooses one of the following ways to grow: grow closer with a Hero (mark a Bond between you and a party member you’ve grown closer to); grow into your changes (rewrite or update one of your Skill or Flaw Tags for a single Motif to better reflect who your Hero is now); or grow toward your goal (mark one Potential on a Motif whose Quest you actively progressed this session).', Results: { Tier3: { Description: 'No roll.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-strike', Name: 'Strike a Nerve', Kind: 'Basic', VirtueId: null, Description: 'When trying to strike the nerve by using manipulation, provocation, or threats to get someone to do what you want or force a reaction, roll +Guile.', Results: { Tier3: { Description: 'They take the bait and do what you intended the best that they can. Gain an appropriate Boon.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They can instead choose one:', ChooseCount: 1, Options: ['They slip: they reveal a tactical detail or a "tell" you can use later.', 'They stumble: gain a critical opportunity and take +1 forward against them.', 'They scare: they fear you. Gain an appropriate Boon.'] }, Tier1: { Description: 'They turn the tables. They may call your bluff or use your pressure as a reason to strike back at you. Either way the GM takes or holds a hard move.', Options: [], ChooseCount: 0 } }, PlayerVariantResults: { Tier3: { Description: 'Mark Bond if they do what you ask.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'They mark Bond between you if they do what you ask. If they don’t do it, they mark a Condition.', Options: [], ChooseCount: 0 }, Tier1: { Description: "It's up to that player to decide how badly you offend or annoy them. Remove one Bond between you. They clear a Condition or mark Potential on any Motif if they do not do what you asked.", Options: [], ChooseCount: 0 } } },
      { Id: 'm-flashback', Name: 'Recall a Flashback', Kind: 'Adventure', VirtueId: null, Description: "At any point a Hero can Recall a Flashback to take an action in the past that has relevance to their current situation — the action you want to take must make sense to have happened. Recalling a Flashback gives you Strain without Resist; the amount you take reflects the severity of the action you “took” in the past: 1 Strain for any ordinary action you could have easily done, 2 Strain for an action with the possibility of complication or some unlikely opportunity, 3 Strain for an intricate or detailed action or set of actions that involved specific opportunities or circumstances. If the action you take in the past would call for a Move, you still roll for that Move and consequences happen accordingly. You can't Recall a Flashback to “undo” a consequence or something that has already occurred.", Results: { Tier3: { Description: "No roll of its own — triggers whichever Move applies to the recalled action.", Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-recuperate', Name: 'Recuperate', Kind: 'Adventure', VirtueId: null, Description: 'Take 2 Strain to remove any one Minor Status. Then, roll +Mettle to advance your Healing Track.', Results: { Tier3: { Description: 'Mark 3 segments on your Healing Track.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'Mark 2 segments on your Healing Track.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'Mark 1 segment on your Healing Track.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-levelup', Name: 'Advance a Motif', Kind: 'Adventure', VirtueId: null, Description: "To take an advancement on a Motif, you need to mark Potential five times. When you mark your fifth Potential, the next time you Make Camp, reduce your Potential Track on that Motif by 5 and choose one option: add a Skill Tag for this Motif; add or remove a Flaw Tag for this Motif (remember, Flaw Tags can help you gain Potential); or gain a Hero Improvement — a Starting Improvement on any Improvement Tree, or one connected by a line to another Improvement you already have on that same tree. Each Improvement can only be chosen once. Then you may rewrite or update any one of your Skill or Flaw Tags for this Motif to better reflect your Hero as they are now. In fiction, at the Camp, you may choose to describe how the party sees your new advancement.", Results: { Tier3: { Description: 'No roll.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-progress', Name: 'Progress the Party', Kind: 'Adventure', VirtueId: null, Description: 'Your party also gets stronger as you adventure together by gaining Rapport. To gain an advancement on your Party’s Motif, you need to mark Rapport five times. When you mark your fifth Rapport, the next time you Make Camp, reduce your Rapport Track by 5 and choose one unique option: add a Skill Tag for your Party Motif; add or remove a Weakness Tag for your Party Motif (Weakness Tags can help you gain Potential); or gain a Party Improvement — a Starting Improvement on any Improvement Tree, or one connected by a line to an Improvement you already have on that same tree. Each Improvement can only be chosen once. In fiction, at the Camp, you may choose to describe how you establish your new advancement.', Results: { Tier3: { Description: 'No roll.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-forge', Name: 'Forge a Bond', Kind: 'Adventure', VirtueId: null, Description: 'After you Make Camp, if you and another PC have 5 or more Bond, you may agree to reduce your Bond by 5 — the ruleset itself leaves this effect “TO BE DETERMINED,” so this app routes it through the existing Bond handshake and lets the table narrate the result. In fiction, at the Camp, you may choose to play out a scene demonstrating the connection you two hold to solidify your new Bond Level and/or demonstrate your new advancement. If you do so, mark one Potential each.', Results: { Tier3: { Description: 'No roll — see the Bond handshake.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-aid', Name: 'Aid', Kind: 'Adventure', VirtueId: null, Description: 'Anyone in the Party can Aid another Hero by removing one Rapport from the Rapport Track to give any other party member +1 on any roll, even after the dice are rolled. In order to spend Rapport this way, the spender needs to truly be able to help — describe how you do so in fiction before giving the +1. Any and all party members can spend Rapport from the Track to help on that same roll; each teammate can only spend one Rapport themselves. Using Rapport this way can take a total miss to a complete success!', Results: { Tier3: { Description: 'No roll of its own — this spends Rapport on someone else’s roll. See Rapport.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-watch', Name: 'Keep Watch', Kind: 'Adventure', VirtueId: null, Description: 'If you Make Camp somewhere potentially dangerous or vulnerable, before heading out on the next leg of your journey, the Party can decide to Keep Watch. First, the players choose a volunteer to lead the watch, and the GM rolls +Nothing and may reveal the result (see Results below). Once the watch begins, the GM can make their move from the list at any time. The Hero on watch then rolls +Wit — if multiple Heroes volunteer or plan on rotating through watches, they can Aid the roll with Rapport as normal. On a 10+ choose 2, on a 7-9 choose 1: You’re alert (take the Alert Boon and rally your party in time for whatever is coming); You choose the turf (get the drop on what’s coming and set up where you choose); You use your senses (ask the GM two questions about what is approaching before it reaches your camp — they may answer only with what your Hero could feasibly find out). On a 6-, despite your best efforts, whatever it is gets to you before you notice it — whether it intends you harm or not — and the GM takes or holds a hard move. If you choose not to Keep Watch and an extended time passes where a threat rears its head, treat the threat as if the Party rolled a 6-.', Results: { Tier3: { Description: 'The night passes without incident.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'The GM chooses one:', ChooseCount: 1, Options: ['The person on watch notices something interesting nearby, related to any Hero’s Motif, Threat, or the Adventure Countdown.', 'One party member of the GM’s choosing doesn’t get much sleep. They wake with the Restless Bane, which doesn’t clear until they can sleep well.', 'Something dangerous approaches. If the person on watch has the Alert Boon or similar, they may rally the party in time.'] }, Tier1: { Description: 'The Party marks Rapport, and a danger will emerge tonight.', Options: [], ChooseCount: 0 } } },
      { Id: 'm-journey', Name: 'Set Out', Kind: 'Adventure', VirtueId: null, Description: 'When you gather your party and venture forth on the first or next leg of your Adventure: choose your Loadout — only after you Make Camp or Enjoy Downtime, each Hero decides if they are traveling with a Light, Medium, or Heavy Loadout; everything else stays in Camp. Then state your destination and decide your route. If your destination is safe to travel to and you are under no time pressure, you simply arrive — describe or play out any scenes on the way, and the GM will tell you how long the Journey took and what else, if anything, happened along the way. If your journey is under time pressure or your destination will take you through dangerous terrain or is otherwise unsafe, Undertake a Perilous Journey: the GM will tell you how many times you’ll need to Make Camp to get there (the answer may be zero); each time you leave Camp you Set Out again until you arrive.\n\nSet Out consists of two phases — choose one Hero for each, then Scout Ahead, then Venture Forth. If there isn’t time to Scout Ahead, roll Venture Forth with disadvantage. Rapport can be spent to Aid as normal on either roll.\n\nScout Ahead: one player takes point and looks for anything helpful or out of the ordinary, roll +Wit. On a 10+ choose 2, on a 7-9 choose 1 — you notice signs of nearby danger (ask the GM what it is and what it might mean, gain the Alert Boon); you discern a beneficial aspect of the terrain, a shortcut, shelter, or tactical advantage (describe it and gain an appropriate Boon); you get the drop on whatever lies ahead (gain the Prepared Boon); you make an interesting discovery (ask the GM). On a 6-, mark Potential and the GM makes a hard move.\n\nVenture Forth: one Hero may then plot the best course as you Venture Forth, roll +Guile. On a 10+, you avoid dangers and distractions and make good time, reaching your destination or a safe place to Make Camp — choose one below and gain +1 Ongoing to any future rolls while you travel. On a 7-9, things don’t go quite as you planned — the GM chooses one below before you reach your destination or a safe place to Make Camp. On a 6-, you make it, but at what cost — mark Potential and the GM makes a hard move: you encounter a significant person, place, or opportunity related to the area and/or your Party Quest; you discover something noteworthy missed by the Scout; the trip takes longer than you planned or you wander off course for a while (everyone marks a Condition or the GM advances a Threat); something or someone is following you, whether or not you’re surprised depends on whether the scout has the Alert Boon.', Results: { Tier3: { Description: 'No roll of its own — see Scout Ahead and Venture Forth above.', Options: [], ChooseCount: 0 }, Tier2: { Description: '—', Options: [], ChooseCount: 0 }, Tier1: { Description: '—', Options: [], ChooseCount: 0 } } },
      { Id: 'm-downtime', Name: 'Enjoy Downtime', Kind: 'Adventure', VirtueId: null, Description: 'When you spend a few days or more in a safe location, you may do as many as you like or can afford of the following. In addition, you can do anything available to you when you Make Camp. Rest: spend 1 Wealth to Recuperate without taking Strain. Recover: take an action that would clear one Condition and instead clear all Conditions. Carouse: for each involved party member, spend 1 Wealth to revel and be merry — everyone involved marks one Bond with another involved Hero. Acquire: spend Wealth to procure new items and equipment available in town, repair your gear, refresh your stock, or acquire services. Train: spend 1 Wealth to mark Potential in a Motif of your choice. Pivot: change a Motif as if you had marked your third Forsake, or as a party decide to change or update the Party Motif. Advance: party members can describe how they are starting or pursuing a long-term goal or project — for a new project the GM and player define the Project Clock (name, description, and how many segments it takes); some projects may require other projects completed or special goals achieved first; party members can work on the same project together; roll +an appropriate Virtue (see Results below). When everyone has finished enjoying downtime, they decide whether days, weeks, or months have passed; the GM then sets the next scene and progresses or starts a new Adventure Countdown and advances any Threats appropriately.', Results: { Tier3: { Description: 'Advance marks 3 segments on the project’s Clock. Every other activity above has no roll of its own.', Options: [], ChooseCount: 0 }, Tier2: { Description: 'Advance marks 2 segments.', Options: [], ChooseCount: 0 }, Tier1: { Description: 'Advance marks 1 segment.', Options: [], ChooseCount: 0 } } },
    ],
    glossary: [
      { Id: 'g-condition', Name: 'Condition', Aliases: ['Conditions'], Definition: 'A marked penalty tied to one of your five Virtues, taken when a move tells you to "mark a Condition." Each Virtue has one specific Condition (Exhausted, Afraid, Hopeless, Irrational, Distracted) that applies a roll penalty to actions using that Virtue until cleared.' },
      { Id: 'g-rapport', Name: 'Rapport', Aliases: [], Definition: 'A party-wide track marked when a move tells you to "mark Rapport." Filling it clears the track and raises Party Level by 1 — see Improvement. Rapport can also be spent directly as Aid — see Aid.' },
      { Id: 'g-motif', Name: 'Motif', Aliases: ['Motifs'], Definition: 'One of the three core aspects of your Hero — each a bucket for its own Skill Tags, Flaw Tags, a Potential track, and a Quest. You choose three Motifs at creation (from the thirteen suggested, or your own) and may rename any of them to fit your character.' },
      { Id: 'g-skill-tag', Name: 'Skill Tag', Aliases: ['Skill Tags'], Definition: 'A freeform word or phrase under a Motif describing something your Hero is good at. Declare a relevant Skill Tag before a roll to add +1; if more than one applies you may Push Yourself, mark a Condition, and add another +1.' },
      { Id: 'g-flaw-tag', Name: 'Flaw Tag', Aliases: ['Flaw Tags'], Definition: 'A freeform word or phrase under a Motif describing a limit or weakness. A relevant Flaw Tag gives -1 to the roll, and acting on it marks Potential on that Motif whether the roll succeeds or fails.' },
      { Id: 'g-quest', Name: 'Quest', Aliases: ['Quests'], Definition: 'A short, player-written goal hanging off one Motif, tracked with three Act Breaks and three Forsakes. Three Act Breaks complete it; three Forsakes abandon it.' },
      { Id: 'g-potential', Name: 'Potential', Aliases: [], Definition: 'A track on each Motif, marked when a move tells you to "mark Potential" (or when you act on a Flaw Tag). Filling a Motif’s track clears it, raises Level by 1, and lets you add a Skill Tag, add or remove a Flaw Tag, or gain a Hero Improvement — see Improvement.' },
      { Id: 'g-improvement', Name: 'Improvement', Aliases: ['Improvements', 'Improvement Tree', 'Hero Improvement'], Definition: 'A permanent pick taken off one of 25 Hero Improvement Trees (11 Combat, 14 Narrative) when a full Motif Potential track clears. Each tree is its own small prerequisite chain: take a tree’s Starting Improvement any time, or any other Improvement on that tree once you already hold one it connects to. Each Improvement can only be taken once. Party Improvements are named in the rules the same way but have no authored trees yet.' },
      { Id: 'g-hold', Name: 'Hold', Aliases: [], Definition: 'A pool of uses granted by a move on a strong hit, spent one at a time — often to ask questions or trigger a listed effect — until it runs out.' },
      { Id: 'g-load', Name: 'Load', Aliases: [], Definition: 'How much you can carry. Each Item has a Load cost (0, 1, or 2); your total carried Load is capped by your Light/Normal/Heavy tier.' },
      { Id: 'g-bond', Name: 'Bond', Aliases: ['Bonds', 'Mark Bond', 'Bond Track', 'Bond Level'], Definition: 'The relationship between two characters, tracked separately from either character’s sheet, plus the 0–5 Bond Track that measures it — marked when a move tells you to "mark Bond" with someone. Filling the Track lets the pair Forge it, raising Bond Level by 1 (to a maximum of 5) and emptying the Track again. Marking Bond and Forging both go through a propose/accept/reject handshake between the two players; spending Bond, unlike either of those, applies immediately with no handshake. A Bond that reaches Level 5 with a full Track locks — its Level can no longer drop, and no more Bond can be spent on it.' },
      { Id: 'g-status', Name: 'Status', Aliases: ['Statuses'], Definition: 'A named, lasting injury held in one of three severity slots — Minor (×3), Major (×2), or Severe (×1). Only the highest-severity Status you hold ever penalizes a roll: Minor is −1, Major is Disadvantage, Severe means rolling 1d6 instead of 2d6. Distinct from Strain (a short-term track that clears at the end of a scene) and from a Condition (always one of the five Virtue-linked penalties). Reduced by Recuperating, or downgraded a severity when your Healing Track fills.' },
      { Id: 'g-strain', Name: 'Strain', Aliases: [], Definition: 'A 5-box short-term harm track that clears completely at the end of the scene or Combat in which it was taken. Mark the box equal to an incoming amount, or the next unmarked box to its right. Resist an incoming amount by rolling + a Virtue to reduce it, or by choosing to take a Status instead (which absorbs a flat 2/4/6 by severity). Armor negates Strain entirely, up to its own limit.' },
      { Id: 'g-healing-track', Name: 'Healing Track', Aliases: [], Definition: 'A 5-segment track advanced by Recuperating (+Mettle: 3/2/1 segments by tier). When it fills, every Status you hold drops one severity (renamed to reflect the improvement, where a slot is free at the lower severity) and the track clears, carrying any remaining segments onto the fresh one.' },
      { Id: 'g-boon', Name: 'Boon', Aliases: ['Boons'], Definition: 'An unranked, freeform situational tag working in your favor — cleared the moment it stops being true. Compared against your Banes on a roll: more relevant Boons than Banes gives Advantage. See Advantage.' },
      { Id: 'g-bane', Name: 'Bane', Aliases: ['Banes'], Definition: 'An unranked, freeform situational tag working against you — cleared the moment it stops being true. Compared against your Boons on a roll: more relevant Banes than Boons gives Disadvantage. See Advantage.' },
      { Id: 'g-crumble', Name: 'Crumble', Aliases: [], Definition: 'What happens when you need to mark a Condition but all five are already marked. You leave the scene — unconscious, fleeing, or otherwise — and then clear one Condition of your choice.' },
      { Id: 'g-subdued', Name: 'Subdued', Aliases: [], Definition: 'What it’s called when no higher Strain box is free and no Status slot is open to absorb any more incoming Strain — a badge the table narrates around, since the ruleset doesn’t (yet) define a consequence for it.' },
      { Id: 'g-scar', Name: 'Scar', Aliases: ['Scars'], Definition: 'A near-permanent consequence a Hero can carry — a lost limb, a lingering nightmare, an unwanted transformation. The old Subdued-triggered choice that used to grant one (Take a Scar / Risk Death / Blaze of Glory) has been retired with no stated replacement; Scars themselves stay on the sheet as free text for whenever the table narrates one.' },
      { Id: 'g-toughness', Name: 'Toughness', Aliases: [], Definition: 'How much an enemy blunts incoming harm in Combat. Medium subtracts 2 from any amount given to it; Heavy treats the amount as though it had been rolled one tier lower.' },
      { Id: 'g-range', Name: 'Range', Aliases: [], Definition: 'How far apart two combatants are: Melee, Close, Far, Very Far, or Out of Range. Maneuver and Shift move you between bands; Engage at Range and Engage in Melee each only work at their own band.' },
      { Id: 'g-unstable', Name: 'Unstable', Aliases: [], Definition: 'What a Hero is called while holding any Major or Severe Status (or an Enemy at half one of its Limits). Unstable has no effect by itself — it’s a threshold other moves and rules can key off, so check whether anything you have cares about it.' },
      { Id: 'g-aid', Name: 'Aid', Aliases: [], Definition: 'Spend 1 Rapport to give another Hero +1 on a roll, even after the dice are already rolled. You can Aid the same roll once per teammate, and Aid from multiple teammates stacks. During Risk Death, Aid costs double — 2 Rapport per +1.' },
      { Id: 'g-wealth', Name: 'Wealth', Aliases: [], Definition: 'A personal resource, freely adjusted on the sheet. Named sinks: spend 1 to roll Follow a Lead with Advantage, or during Enjoy Downtime to Rest, Carouse, Acquire, or Train.' },
      { Id: 'g-treasure', Name: 'Treasure', Aliases: [], Definition: 'A personal resource, freely adjusted on the sheet like Wealth. Ruleset-V0.6.md names no Wealth-distinct sink for Treasure any more — Carouse spends Wealth now — so it stays a freely adjusted resource with no automated hook.' },
      { Id: 'g-advantage', Name: 'Advantage', Aliases: ['Disadvantage'], Definition: 'Roll 3d6 and keep the best two (Advantage) or worst two (Disadvantage) instead of the usual 2d6 — decided by comparing your Boons and Banes relevant to the roll: more Boons is Advantage, more Banes is Disadvantage, a tie (including none of either) is Normal. A Major Status is a separate source of Disadvantage the ruleset doesn’t say how to combine with a Boon/Bane-driven one — both are shown, and the table resolves it.' },
      { Id: 'g-consequence', Name: 'Consequence', Aliases: ['Burdened', 'Compromised', 'Delayed', 'Depleted', 'Exposed', 'Consequences'], Definition: 'One of five named outcomes on Invoke Expertise and Take a Risk: Burdened (a worse outcome, hard choice, or price to pay), Compromised (the situation escalates), Delayed (you take too long; things change meaningfully), Depleted (expend a resource or break a useful item), or Exposed (draw unwanted attention or leave a traceable trail). Replaces the old Attrition/Detection/Danger/Delay/Sacrifice vocabulary.' },
      { Id: 'g-camp-asset', Name: 'Camp Asset', Aliases: ['Camp Assets'], Definition: 'A magic item the party is afforded at creation to help them set up camp, leveling up through Tiers as the party progresses. Pick one from the library, or write your own on the spot.' },
      { Id: 'g-camp-action', Name: 'Camp Action', Aliases: ['Camp Actions'], Definition: 'One of a handful of things each player may do at Make Camp — set or change the Party Goal, rewrite or update one of your Skill or Flaw Tags, use a Camp Asset, or progress a personal project Clock. Each player gets Party Level + 1 of these per Camp.' },
      { Id: 'g-push-yourself', Name: 'Push Yourself', Aliases: [], Definition: 'When more than one of your Skill Tags applies to a roll, mark one Condition to add a second +1 on top of your declared Skill Tag’s own +1.' },
      { Id: 'g-set-out', Name: 'Set Out', Aliases: [], Definition: 'Gathering the party and venturing forth on the next leg of an Adventure — Choose your Loadout, then either simply arrive at a safe destination or Undertake a Perilous Journey through Scout Ahead and Venture Forth. Formerly named "Undertake a Journey."' },
      { Id: 'g-opposition-clock', Name: 'Opposition Clock', Aliases: [], Definition: 'The most common Clock — a Success track and a Failure track, both starting at 0 Headway. Risking 1-3 Headway before a roll: a 10+ adds the risked Headway to Success, a 7-9 adds it to both, a 6- adds it to Failure.' },
      { Id: 'g-threat-clock', Name: 'Threat Clock', Aliases: ['Threat Clocks'], Definition: 'A player-facing Clock for a brewing danger the Heroes have learned of — a Name, description, Goal, Skill Tags, and Developments (roughly one per segment), sized 2-4 for a nearby Threat, 4-6 regional, 7+ realm-spanning. A GM may promote one to the campaign\'s Quest Board. Advances by the GM\'s own hand, often at Make Camp — this app doesn\'t advance a neglected Threat on its own.' },
      { Id: 'g-project-clock', Name: 'Project Clock', Aliases: [], Definition: 'A Hero\'s own downtime pursuit — building, crafting, enchanting, researching, and the like. Give it a name, description, and Goal; progress it by rolling + an appropriate ability and reporting the tier (10+: 3 segments, 7-9: 2, 6-: 1), the same way Enjoy Downtime\'s Advance and a Camp Action already work.' },
      { Id: 'g-development', Name: 'Development', Aliases: ['Developments'], Definition: 'A planned consequence tied to one segment of a Threat Clock, triggered whenever it best serves the pacing rather than strictly in order — early Developments introduce the Threat lightly, later ones raise the stakes.' },
      { Id: 'g-headway', Name: 'Headway', Aliases: [], Definition: 'The amount (1-3) a Hero risks before rolling to progress an Opposition Clock — gained by the Heroes on a 10+, by both sides on a 7-9, or by the opposition alone on a 6-.' },
      { Id: 'g-villain', Name: 'Villain', Aliases: ['Villains'], Definition: 'The antagonist driving an Adventure’s conflict — a monster, person, or anomaly with a Goal, a Scar, Skill Tags, Resources, Powers, Attacks, Resistances and Vulnerabilities, and Status Limits. A Villain doesn’t need to be killed or even defeated to conclude an Adventure — their Goal only needs to be thwarted.' },
      { Id: 'g-npc', Name: 'NPC', Aliases: ['NPCs', 'Non-Player Character'], Definition: 'A supporting-cast character with a Type (their function to you as a GM — Meddler, Minion, Gossip, Ally, Guard, Opportunist, Skeptic, Victim, or Witness), a Goal, and Skill Tags. A Combatant NPC gets Status Limits, same as an Enemy.' },
      { Id: 'g-location', Name: 'Location', Aliases: ['Locations'], Definition: 'A place the Heroes are expected to spend time during an Adventure — 3 Aspects the Heroes can interact with, plus a Location Type (Nexus, Deathtrap, Lair, Citadel, Lab, Archive, Labyrinth, Gaol, or Wilds) describing its purpose.' },
    ],
    enemies: [
      { Id: 'en-brigand', Name: 'Brigand', Description: 'A rank-and-file thug, more dangerous in numbers than alone.', IsBoss: false, Toughness: 'None', StatusLimits: [{ StatusName: 'Hurt', Limit: 4 }, { StatusName: 'Scared', Limit: 3 }] },
      { Id: 'en-warden', Name: 'Iron Warden', Description: 'A plated sentinel bound to guard a single door until it falls.', IsBoss: false, Toughness: 'Heavy', StatusLimits: [{ StatusName: 'Hurt', Limit: 6 }] },
    ],
    /** Ruleset-V0.5.md never names an actual Camp Asset — only the generic concept ("a magic camp
     *  item that facilitates setting up their camp... it levels up as they progress into the
     *  tiers"). These three are illustrative starting examples, same spirit as the two seeded
     *  Enemies above; a party can also just write their own ad-hoc one at Camp (see
     *  `PartyCampAsset`). */
    campAssets: [
      { Id: 'ca-tent', Name: 'Ever-Warm Tent', Description: 'A canvas pavilion that pitches itself in minutes and holds the chill outside no matter the season.', Tier: 1, Effect: 'Camp always feels safe and comfortable, regardless of weather.' },
      { Id: 'ca-hearth', Name: 'Hearthstone', Description: 'A fist-sized stone that lights a fire from nothing and never needs fuel.', Tier: 1, Effect: 'Camp always has light and warmth, even with no wood to burn.' },
      { Id: 'ca-wardposts', Name: 'Warding Posts', Description: 'Four carved stakes that hum faintly when driven into the ground around a camp.', Tier: 2, Effect: 'Anything hostile approaching the camp perimeter announces itself — treat Keep Watch’s 6- result as a 7-9 instead.' },
    ],
    /** Ruleset-V0.5.md's "Villains and Enemies in Combat" section gives exactly one worked example
     *  — Grizza the Tall — complete with Goal, flavor text, and a Toughness/Status-Limits stat
     *  block; seeded here verbatim rather than invented. `Aspects`/`Scar`/`SkillTags`/`Resources`/
     *  `Powers`/`Attacks`/`Resistances`/`Vulnerabilities` fill in the doc's own "a Villain is
     *  comprised of" checklist from that same worked example's flavor text and the earlier Adventure
     *  Concept text ("a pack of goblins... steal the blacksmith's daughter... to cleanse the ancient
     *  tomb they've recently overtaken") — the doc doesn't spell every one of these fields out for
     *  Grizza by name, so this is a reasonable, clearly-attributed fill-in, not a second invented
     *  Villain. */
    villains: [
      {
        Id: 'vil-grizza',
        Name: 'Grizza the Tall',
        Aspects: ['Taller-Than-Average Goblin', 'Draped in Rotting Furs', 'Spider-Eyed Hat'],
        Goal: 'Prove her power to her new goblin clan and earn the family she never had, backed by a claimed connection to the divine Vuldec, Lord of Goblins.',
        Scar: 'Shunned by her own clan as a child, then watched its leaders turn even her friends against her — she has spent every day since proving she needs none of them.',
        SkillTags: ['Command Over Lesser Magic', 'Commands Fierce Loyalty', 'Never Forgets a Slight'],
        Resources: ['Her Goblin Clan', 'The Ancient Tomb They’ve Overtaken', 'Claimed Favor of Vuldec, Lord of Goblins', 'The Blacksmith’s Captive Daughter'],
        Powers: 'Commands lesser magic — enough to convince a clan of goblins that she truly speaks for Vuldec.',
        Attacks: 'Fall to my Power! — closes to Melee and lashes out, dealing Wounded and Wobbly. Fearsome Yell — a deafening roar that rattles everyone nearby, dealing Deafened to all who hear it.',
        Resistances: 'Fear and intimidation alone don’t rattle her — she’s used to being underestimated.',
        Vulnerabilities: 'Her connection to Vuldec is a bluff; exposing it in front of her clan strips her authority instantly.',
        Toughness: 'Medium',
        StatusLimits: [{ StatusName: 'Hurt', Limit: 12 }, { StatusName: 'Scared', Limit: 13 }, { StatusName: 'Tricked', Limit: 9 }],
      },
    ],
    /** Two illustrative NPCs pulled from the same Grizza/goblin-tomb material Ruleset-V0.5.md's
     *  worked example centers on — Rosa is the doc's own named Hook figure ("Rosa the Blacksmith
     *  barges into wherever the Heroes are, pleading for someone capable to travel into the woods
     *  and find where the goblins dragged off her daughter"); Skreel is invented to show a
     *  Combatant-NPC entry (Type: Minion, real Status Limits) alongside Rosa's non-Combatant one. */
    npcs: [
      { Id: 'npc-rosa', Name: 'Rosa the Blacksmith', Aspects: ['Soot-Stained Apron', 'Steady Hammer Hand', 'Won’t Stop Until Her Daughter’s Found'], Type: 'Ally', Goal: 'Get her daughter back from the goblins, whatever it takes.', HeroConnection: '', SkillTags: ['Forge and Repair', 'Knows Every Road Out of Town', 'Stubborn as the Anvil'], IsCombatant: false, StatusLimits: [{ StatusName: 'Overwhelmed', Limit: 2 }] },
      { Id: 'npc-skreel', Name: 'Skreel', Aspects: ['Notched Ear', 'Twitchy and Underfed', 'Carries Too Many Knives'], Type: 'Minion', Goal: 'Stay in Grizza’s good graces, and out of the way of her temper.', HeroConnection: '', SkillTags: ['Knows the Tomb’s Back Ways', 'Better at Running Than Fighting', 'Eavesdrops on Everyone'], IsCombatant: true, StatusLimits: [{ StatusName: 'Hurt', Limit: 6 }] },
    ],
    /** Three illustrative Locations, same Grizza/goblin-tomb material — one for each of the doc's
     *  own suggested starting points ("the general town or area, where the Villain resides, places
     *  where victims or witnesses... reside"). `CustomMoves` stays empty for all three — the doc's
     *  own "Optionally, one or more custom moves" is left unauthored rather than invented. */
    locations: [
      { Id: 'loc-hollow-bend', Name: 'Hollow Bend', Aspects: ['The Blacksmith’s Forge Still Burns', 'Rumors Travel Faster Than News', 'One Road In, One Road Out'], LocationType: 'Nexus', CustomMoves: '' },
      { Id: 'loc-sunken-tomb', Name: 'The Sunken Tomb', Aspects: ['Goblin Totems Line the Entrance', 'Ancient Wardstones, Half-Buried', 'The Air Smells of Old Blood'], LocationType: 'Lair', CustomMoves: '' },
      { Id: 'loc-whispering-wood', Name: 'The Whispering Wood', Aspects: ['Trails That Double Back on Themselves', 'Old Goblin Totems Nailed to Trees', 'Something Always Watching From the Dark'], LocationType: 'Wilds', CustomMoves: '' },
    ],
    settings: {
      Id: 'set-1',
      PotentialTrackLength: 5,
      RapportTrackLength: 5,
      BondTrackLength: 5,
      StrainTrackLength: 5,
      ConditionFloor: -3,
      HealingTrackLength: 5,
      MinorStatusSlots: 3,
      MajorStatusSlots: 2,
      SevereStatusSlots: 1,
      GlossaryAutoLink: true,
    },
    loadTiers: [
      { Key: 'Light', Base: 3, Note: 'You move quickly, have +1 Speed in Combat, and are relatively inconspicuous.' },
      { Key: 'Normal', Base: 5, Note: 'You move normally and look like a prepared adventurer.' },
      { Key: 'Heavy', Base: 6, Note: 'You move slower than normal, have −1 Speed in Combat, and look like a particularly armed combatant.' },
    ],
  };
}
